### ISSUE TITLE
403 Forbidden on Algolia search

### ISSUE THREAD

**Issue by kalynrobinson** [saleem-hadad/larecipe#101]
**Describe the bug**
Domain changes on Algolia's end cause certain searches to fail and return 403 Forbidden because the application ID is not correct. (Presumably. I don't actually know anything about Algolia.)

By default (and even when passing in `appId`), docsearch sends its request to `http://bh4d9od16a-dsn.algolia.net`. In my case, I need it to be `q37nqdq7nw-dsn.algolia.net`

**To Reproduce**
* Use any Algolia API key where the Application ID is NOT `bh4d9od16a`
* Attempt to search

**Expected behavior**
Should return 200.

**Notes**
Docsearch doesn't seem to recognize `appId` and will not use the supplied value.

```javascript
// AlgoliaSearchBox.vue
docsearch({
    appId: "NOTREAL",
    apiKey: this.algoliaKey,
    indexName: this.algoliaIndex,
    inputSelector: '.algolia-search-input',
    algoliaOptions: { 'facetFilters': ["version:" + this.version] },
    debug: false
})
```

E: Actually, docsearch not accepting `appId` might just be user error. 🙄 Will investigate more later.

**Comment by kalynrobinson** [comment]
Actually, docsearch not accepting `appId` might just be user error. 🙄 Will investigate more later.

**Comment by saleem-hadad** [comment]
is this issue still there?

**Comment by jadamec** [comment]
I've same issue, how to fix it, please?

**Comment by Machecek** [comment]
Same issue here. It's defined directly in /vendor/binarytorch/larecipe/publishable/assets/js/app.js , this value should be loaded from config

**Comment by takielias** [comment]
@saleem-hadad I'm still facing the same issue. Could you please check?
