### ISSUE TITLE
Getting --> app.js:1 ReferenceError: forceDarkSidebar is not defined

### ISSUE THREAD

**Issue by mrompo** [saleem-hadad/larecipe#102]
Hello, after execute "composer update" I am getting next error:

```js
app.js:1 ReferenceError: forceDarkSidebar is not defined
```

I executed upgrade procedure:

```bash
php artisan vendor:publish --tag=larecipe_config --force
php artisan vendor:publish --tag=larecipe_assets --force
```

But doc continue without rendering.
Some idea?

**Comment by saleem-hadad** [comment]
try to run
```
php artisan view:clear
php artisan cache:clear
```

**Comment by mrompo** [comment]
It solved the issue.
Easy and simply!!
Thanks

**Comment by saleem-hadad** [comment]
Most welcome 👍

**Comment by christophrumpel** [comment]
I still have the same error. All the solutions above did not help. Should I create a new issue?

**Comment by christophrumpel** [comment]
Ok, no idea why but today when I turned on my laptop it worked again 🤷🏼‍♂️. Not sure why. But you can close the issue again till I know more.
