### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by mahongcan** [saleem-hadad/larecipe#104]
bug

![image](https://user-images.githubusercontent.com/38125573/54584876-88d65680-4a53-11e9-95df-2c3a386e89fa.png)

**Comment by saleem-hadad** [comment]
hmm, can you provide more details on this? I mean version/browser .. etc

**Comment by mahongcan** [comment]
Google, version 73.0.3683.75

Larecipe, version 1.3

A bug occurs when you slide left and right with the mouse
