### ISSUE TITLE
Markdown Checkboxes

### ISSUE THREAD

**Issue by TheFrankman** [saleem-hadad/larecipe#107]
**Is your feature request related to a problem? Please describe.**
You do not seem to support markdown checkboxes i.e. 

Markdown : 
```
- [x] This box is checked
- [ ] This box is unchecked
```
Output :
- [x] This box is checked
- [ ] This box is unchecked

Is this a bug ? Is this feature in the works ?

**Comment by TheFrankman** [comment]
I've spotted the vue component but markdown would also be good.

**Comment by saleem-hadad** [comment]
yup that will be cool as well, can you propose a PR, please?
