### ISSUE TITLE
LaRecipe V2 Theme and Component Path

### ISSUE THREAD

**Issue by TheFrankman** [saleem-hadad/larecipe#108]
**My Problem is a Feature**
Can we make the path to the custom themes / assets configurable in the LaRecipe config.
Everything works great with the functionality, it's not a serious issue, but having these directories in the project root seems a bit messy. Preferable i'd have it in the resources/docs directory. But perhaps just better to make it configurable.

**Comment by saleem-hadad** [comment]
@TheFrankman Thanks for sharing
Yes, I think it's a good idea, I'll consider that soon :)

**Comment by saleem-hadad** [comment]
Added now, will be available in the next version v2.1 soon :)

**Comment by josegus** [comment]
amazing, when will be the 2.1 available? Don't forget to update the docs, please, this is a little bit confusing:

![image](https://user-images.githubusercontent.com/13947849/57465884-83c0a700-724d-11e9-8389-9e0c54c77cfc.png)

An example would be great.
