### ISSUE TITLE
Nicer UI switcher

### ISSUE THREAD

**Issue by arxeiss** [saleem-hadad/larecipe#109]
First let me thank you for this amazing tool. I really love it! Such an amazing job. But it has small UI flaw, the switch.

I don't like the bad pixels around the inner part which can be visible on some pixels-ratios. 
![image](https://user-images.githubusercontent.com/5103109/55583781-01f7ce00-5723-11e9-9b6c-e5ffa09efd0e.png)

If you add some border to switch, I think it looks bit better.
    
    .switch-label{ border: 2px solid white; }

Will result into this

![image](https://user-images.githubusercontent.com/5103109/55583911-4a16f080-5723-11e9-80ba-45d13272ea40.png)

---

Sorry for not creating merge request, but I can do it later if will be better for you

**Comment by saleem-hadad** [comment]
Thank you @arxeiss nice catch, I like it 👍 
I'll update this soon 💃
