### ISSUE TITLE
add some padding when highlighting long sentence

### ISSUE THREAD

**Issue by 3llomi** [saleem-hadad/larecipe#110]
**Describe the bug**
when using highlighting using ` ` there is no spacing between words

**To Reproduce**
the words getting too close to each other when highlighting long sentence

**Expected behavior**
it should has some spacing or padding

**Screenshots**
![Capture](https://user-images.githubusercontent.com/8546946/55833082-44e8e580-5b17-11e9-9fa3-0aa606a76b2c.PNG)

**Desktop (please complete the following information):**
 - OS:Windows 10
 - Browser :Chrome
 - Version :73.0.3683.86

**Comment by arxeiss** [comment]
I think this is not simply possible, because the main limitation is CSS `display: inline` here. You don't know where the break will happen. And yes, there is padding already, but inline element will break into more lines like this.

**Comment by saleem-hadad** [comment]
I think the best solution is to increase the line-hight (leading-normal/loose), I'll try tomorrow

**Comment by saleem-hadad** [comment]
<img width="634" alt="Screenshot 2019-04-13 at 2 12 24 AM" src="https://user-images.githubusercontent.com/12780866/56057466-753bb880-5d91-11e9-9344-88e23186acc5.png">

**Comment by saleem-hadad** [comment]
will be available soon in the next version
