### ISSUE TITLE
Copy to clipboard is missing

### ISSUE THREAD

**Issue by suhardiyan** [saleem-hadad/larecipe#111]
Hi, im using this md :

```
```json
{
  "firstName": "John",
  "lastName": "Smith",
  "age": 25
}```
```

The "copy" button is missing, How can I enable that button just like an example in laracipe documentaion website?

Its lack documentations

**Comment by saleem-hadad** [comment]
Hi @suhardiyan 
thank you for sharing this, can you tell me which version are you using? because cope to clipboard feature has been added to version 2 of LaRecipe and it comes out of the box you don't have to configure anything

**Comment by suhardiyan** [comment]
Hi, updated and also fresh install larecipe on laravel 5.4 generate error like this:
```

(3/3) ErrorException
Class 'LaRecipe' not found

in 1058e861cc3ac5627afc09ac81741b210843e702.php line 39
```

please help
@saleem-hadad

**Comment by suhardiyan** [comment]
Updated.

I added 

> 'LaRecipe' => BinaryTorch\LaRecipe\Facades\LaRecipe::class,

To Class Alliasses

After that, I open using artisan serve, the screen is blank..

**Comment by saleem-hadad** [comment]
Hi @suhardiyan, I mentioned in the docs if you are using Laravel 5.4  you will need to add the LarecipeServiceProvider manually to your providers' array.

add this line in your `config/app.php`:

```php
'providers' => [
        /*
         * Package Service Providers...
         */
        BinaryTorch\LaRecipe\LaRecipeServiceProvider::class,
    ],
```

**Comment by suhardiyan** [comment]
Hi @saleem-hadad  ikr bro.

I open using artisan serve the screen is blank. Im installing larecipe from fresh installed laravel 5.4

**Comment by saleem-hadad** [comment]
Hi
Yes the
