### ISSUE TITLE
Add support for Lumen

### ISSUE THREAD

**Issue by abishekrsrikaanth** [saleem-hadad/larecipe#115]
**Is your feature request related to a problem? Please describe.**
It currently doesn't seem to work with lumen. I am able to add the package, but fails with errors 

```
 Call to undefined function public_path() 
```
I added the function `public_path`, but then I got this error 

```
Call to undefined method Laravel\Lumen\Routing\Router::name()
```

This will be great tool to maintain api documentation and other internal documentation for the lumen project as well.

**Comment by arxeiss** [comment]
I think, this will never be possible. Lumen does not have Blade support, response must be JSON etc.
I suggest you to look to Swagger for API documentation.

**Comment by saleem-hadad** [comment]
Yes as @arxeiss said, it's not possible and actually no plan to support it, sorry.
