### ISSUE TITLE
Enable SideBar by deafult

### ISSUE THREAD

**Issue by MakamuEvans** [saleem-hadad/larecipe#120]
An using v2.

I have added 
'show_side_bar'  => true,
but still sidebar is disabled by default.

**Comment by saleem-hadad** [comment]
I tried this, it's working, just make sure you clear the application store from your browser

**Comment by kitred** [comment]
Hi @saleem-hadad

I checked the history of the files and I can confirm that this is not working anymore with v2. Here are some of the lines that supports this feature.

`resources/js/larecipe.js:35` [v2](https://github.com/saleem-hadad/larecipe/blob/v2.1.3/resources/js/Larecipe.js)

`sidebar:` false,`

and here's the previous feature for [v1.3](https://github.com/saleem-hadad/larecipe/commit/1bb3fc4b8f9dd6e75fd8cff21a3a9b8f41974784#diff-f475d31974d883cafdf388554ac723c0) comparison.

Thank you! Your work is very beautiful btw. Keep it up!
