### ISSUE TITLE
Some config changes not taking effect

### ISSUE THREAD

**Issue by AlexGodbehere** [saleem-hadad/larecipe#121]
I'm trying to set a custom logo and remove the application text, but the changes to my config file aren't making any difference. I can change the colour scheme and the favicon, but not the logo. Config file:
```
/*
		|--------------------------------------------------------------------------
		| Appearance
		|--------------------------------------------------------------------------
		|
		| Here you can add configure the appearance of your docs. For example,
		| you can set the primary and secondary colors that will give your
		| documentation a unique look. You can set the fav of your docs.
		|
		|
		*/

		'ui' => [
			'show_app_name' => false,
			'logo'          => '/assets/img/logo.svg',
			'fav'           => '/assets/img/favicon.png',
			'theme'         => 'light',
			'back_to_top'   => true,
			'show_side_bar' => true,
			'colors'        => [
				'primary'   => '#ffd04b',
				'secondary' => '#3f454a'],],

		/*
```

I've tried `cache:clear` and `config:clear` but these don't seem to be having any effect.

**Comment by saleem-hadad** [comment]
Hi
May I know which version of larecipe are you using?
if >v2 you can edit the logo by going to the resources/views/vendor/larecipe/partials/navbar.blade.php and change the logo from there.

**Comment by AlexGodbehere** [comment]
Ah, perfect! Is this mentioned in the documentation or did I miss it?
