### ISSUE TITLE
Disable smooth scrolling

### ISSUE THREAD

**Issue by AlexGodbehere** [saleem-hadad/larecipe#122]
Is there a way to disable the 'smooth' scrolling on the sidebar? The website and documentation also have this and it makes them borderline unusable!

**Comment by saleem-hadad** [comment]
hmm, there's no way actually. sorry, Alex.

**Comment by AlexGodbehere** [comment]
I must be missing something here. Why does the scrolling behave erratically in the first place? Is there a package being used to 'improve' the experience? Not giving users the ability to disable this feature is a huge oversight in my opinion, especially when it makes using the package a horrible experience. As mentioned before, the website also has this. Was it a design decision?

**Comment by AlexGodbehere** [comment]
@saleem-hadad Any comment on this? The scrolling just simply doesn't work on any of my devices. In my opinion, it's really trying to solve a problem that didn't exist and has just made the experience worse.

**Comment by Fuhrmann** [comment]
Yeah, same problem here. It would be better to have an option to turn off the smooth.
