### ISSUE TITLE
Level 2 indentation doesn't seem to render correctly

### ISSUE THREAD

**Issue by AlexGodbehere** [saleem-hadad/larecipe#123]
If I have more than one level of pages, the whole page group toggles **bold** when any one of the children is selected. Also, the indentation doesn't indent far enough. Is this currently an unsupported feature or am I not using this correctly?

```
- ## Title
    - [Overview](/docs/{{version}}/banking/banking_overview)
    - [Accounts](/docs/{{version}}/banking/bank_accounts)
        - [Opening a New Account](/docs/{{version}}/banking/opening_a_new_account)
        - [Closing an Account](/docs/{{version}}/banking/deleting_your_account)
```

**Comment by saleem-hadad** [comment]
Hi @AlexGodbehere 
can you provide a screenshot?

**Comment by fhusquinet** [comment]
I don't have the same issue though regarding the bold I would agree on the fact the the indentation isn't as big as it should be on the 2nd level elements.

[Image](https://imgur.com/NXEvCKb)

Code:
```
- ## Application API
    - [Introduction](/{{route}}/{{version}}/application-api/introduction)
    - [Versioning](/{{route}}/{{version}}/application-api/versioning)
    - [Authentification](/{{route}}/{{version}}/application-api/authentification)
    - [Pages](/{{route}}/{{version}}/application-api/pages)
    - [Requests](/{{route}}/{{version}}/application-api/requests)
    - [Messages](/{{route}}/{{version}}/application-api/messages)
    - [Projects](/{{route}}/{{version}}/application-api/projects)
    - [Misc](#)
        - [Endpoints](/{{route}}/{{version}}/application-api/misc/endpoints)
        - [HTTP Codes](/{{route}}/{{version}}/application-api/misc/http-codes)
```

**Comment by saleem-hadad** [comment]
@fhusquinet  thank you dude for sharing this
glad you enjoyed it
I'll investigate on this issue I guess it's just a simple CSS fix

**Comment by saleem-hadad** [comment]
the fix will be available soon in the next version
<img width="343" alt="Screenshot 2019-07-09 at 11 24 13 AM" src="https://user-images.githubusercontent.com/12780866/60867843-c813f780-a23c-11e9-9b28-cfc724ccda37.png">
<img width="265" alt="Screenshot 2019-07-09 at 11 24 17 AM" src="https://user-images.githubusercontent.com/12780866/60867844-c813f780-a23c-11e9-9f0c-315d9bd5b683.png">
<img width="265" alt="Screenshot 2019-07-09 at 11 24 21 AM" src="https://user-images.githubusercontent.com/12780866/60867845-c813f780-a23c-11e9-8e62-e43bdca8f8aa.png">
