### ISSUE TITLE
Language specific code tabs

### ISSUE THREAD

**Issue by steffen25** [saleem-hadad/larecipe#124]
**Is your feature request related to a problem? Please describe.**
Often when you show code snippets in your documentation you'll want to support different programming languages. I could not find any examples in your documentation to this and therefore I was wondering if this is going to be added? I could probably write a custom vue component to get what I need but I would rather ask the community first.

You can add a code snippet for each language but that will get bloated quickly making it a bad user experience.

See above.

**Describe the solution you'd like**
A simple way to write language specific code tabs e.g.

```
<!--JavaScript-->
```js
console.log('Hello, world!');
```
```
<!--Python-->
```py
print('Hello, world!')
```

**Describe alternatives you've considered**
Inspiration and screenshot taken from Docusaurus

**Additional context**
![Screenshot 2019-05-17 at 18 23 15](https://user-images.githubusercontent.com/9927227/57942259-45705b00-78d1-11e9-8150-8aec1592e83f.png)

**Comment by saleem-hadad** [comment]
I thought of this long time ago, it ganna be awesome
I'll add it to the future development #6 
thank you @steffen25 🌸
