### ISSUE TITLE
Problem inserting images

### ISSUE THREAD

**Issue by fabri01** [saleem-hadad/larecipe#128]
**Describe the bug**
I've created an images folder inside the docs/version folder I'm working on. Then I used the markdown syntax I found into the docs for images (![image](url)) and linked the select images. It works on "preview" mode but when I try to load the browser the images is not showed. 

Is there something I miss ?

**Comment by saleem-hadad** [comment]
Hi @fabri01 
thanks for sharing this issue.
to render the images, make sure you put them in the public folder, not inside the docs folder.
for instance:
```
-public
    -images
        -image.png
```

then you put the image url as this: `/images/image.png`

**Comment by josegus** [comment]
but this only works if i run my project with artisan run. ¿How can i use relative paths?

**Comment by bilogic** [comment]
@saleem-hadad hmm, doesn't entirely make sense especially if these docs need to be behind an authentication.

**Comment by saleem-hadad** [comment]
@bilogic Thanks for raising your concern, I was late to reply because I didn't see the notification (so many of them)
but happy to know your approach to solving this?
you can share your thoughts and discuss before starting the PR

**Comment by bilogic** [comment]
@saleem-hadad 

I'm coming from the user's point of view with the following assumptions:

1. Images should also be version controlled (all content should be version controlled regardless of media)
2. Also assume that there is minimal image duplication, so, no benefit in placing them in a separate folder
3. Most users should be using some kind of local live preview editor, e.g. VSCode, so having images and markdown side by side will allow these editor to properly preview them

I haven't looked at the code in depth, but I don't think the above are that challenging. What do you think?
