### ISSUE TITLE
How can I generate .md file for this package?

### ISSUE THREAD

**Issue by MiladAheshmeh** [saleem-hadad/larecipe#130]
How can I generate .md file for this package?

**Comment by jadamec** [comment]
You could probably use `arecipe:docs`.

  `larecipe:docs`                 Generate docs structure with indexes for all your documentation's versions
 ` larecipe:install`              Install LaRecipe and publish the required assets and configurations.

**Comment by saleem-hadad** [comment]
if you mean writing a new .md file, then there is no way to automate this process, you have to create the .md files manually.
regards

**Comment by saleem-hadad** [comment]
thanks, @jadamec
