### ISSUE TITLE
Update parsedown-extra version

### ISSUE THREAD

**Issue by laurenwilliams92** [saleem-hadad/larecipe#131]
"erusev/parsedown-extra": "^0.7.1"

This version does not work with the latest "erusev/parsedown" that get's pulled down on install.

i.e headers are unusable

![larecipe](https://user-images.githubusercontent.com/32837730/59436019-bb8bb300-8de6-11e9-9268-71019d40ca24.PNG)

**Comment by saleem-hadad** [comment]
I've tested the installation now and it seems there's no issue so far :/

<img width="737" alt="Screenshot 2019-07-08 at 5 15 37 PM" src="https://user-images.githubusercontent.com/12780866/60813110-09a49400-a1a4-11e9-9067-1ea5f29bfcd6.png">

which version of laravel you have?

**Comment by laurenwilliams92** [comment]
The installation runs fine, it’s when you go to add a header onto a page that it falls over.

**Comment by laurenwilliams92** [comment]
This is still an issue, where I can not use any headers.

**Comment by bamono** [comment]
I'm also having this issue

**Comment by laurenwilliams92** [comment]
This is still an issue, unable to use markdown headers still.

**Comment by dahousecat** [comment]
When I add text like this:

```
# h1
````

I get this error:

```
Undefined index: text
```

This is a code block that shows the problem lies on line 209 - the line with preg_match.

```
    protected function blockHeader($Line)
    {
        $Block = parent::blockHeader($Line);
 
        if (preg_match('/[ #]*{('.$this->regexAttribute.'+)}[ ]*$/', $Block['element']['text'], $matches, PREG_OFFSET_CAPTURE))
        {
            $attributeString = $matches[1][0];
            $Block['element']['attributes'] = $this->parseAttributeData($attributeString);
            $Block['element']['text'] = substr($Block['element']['text'], 0, $matches[0][1]);
        }
        return $Block;
    }
```

The same error happens with any for of title. E.g.

```
# H1
## H2
### H3
#### H4
##### H5
###### H6

Alt-H1
======

Alt-H2
------
```

Not using any titles fixes the problem but this is annoying as is a great package apart from this.
