### ISSUE TITLE
Localize "SEARCH..." of the Search Bar

### ISSUE THREAD

**Issue by jadamec** [saleem-hadad/larecipe#134]
**Is your feature request related to a problem? Please describe.**
There should be an option for translation of the "Search..." string and also other strings, but I think there're no more of them. Btw, amazing package. Thanks for your hard work!

**Describe the solution you'd like**
Localization could be done either by config file or better option would probably be through resources/lang.

**Comment by saleem-hadad** [comment]
Yup, I'm working on the localization feature but I need a bit of time since I'm working full-time
Thanks for sharing :)

**Comment by jadamec** [comment]
Anything new about this, please? Thanks!

**Comment by jadamec** [comment]
+1
