### ISSUE TITLE
[Chrome] Unable to preventDefault inside passive event listener due to target being treated as passive. 

### ISSUE THREAD

**Issue by bluetinkwok** [saleem-hadad/larecipe#135]
I get this error in Chrome Console and a the same error will continuously generate as I scroll

**Comment by saleem-hadad** [comment]
May I know which version of LaRecipe you have?

**Comment by bluetinkwok** [comment]
2.1.3

**Comment by saleem-hadad** [comment]
I guess that due to the smoothwebscroll library in the front-end part, 
I'll try to fix it soon 👍

**Comment by bluetinkwok** [comment]
Thanks.

And I got another error at the initail stage when I downloaded the library.

Uncaught SyntaxError: Invalid or unexpected token
overview:152 Uncaught ReferenceError: config is not defined
    at overview:152
overview:160 Uncaught ReferenceError: LaRecipe is not defined
    at overview:160

I find tge error is caused in : vendor\binarytorch\larecipe\resources\views\default.blade.php   line 62
window.config = @json([]);

once I changed to 
window.config = [];

the error is fixed.

**Comment by xadjek** [comment]
> I guess that due to the smoothwebscroll library in the front-end part,
> I'll try to fix it soon

Hello. Any updates on this issue? I have also such error at chrome devtools

**Comment by qLutCh55** [comment]
I see smoothscroll-for-websites updated to "1.4.10" and i see a issue is closed on the package regaring this chrome bug. So maybe just update package.json?

**Comment by saleem-hadad** [comment]
the fix will be in the next version, already updated the dep.
