### ISSUE TITLE
Index / Right Sidebar not scrollable

### ISSUE THREAD

**Issue by fabianpnke** [saleem-hadad/larecipe#137]
**Describe the bug** / **To Reproduce**
I added the follwing pages to the Index / Right Sidebar. All Sections after "6. Stornierung" are not showing. And its not possible to scroll any further in the index. The normal content is scrollable.

**Used Index**
- [Übersicht](#übersicht)
	- [1. Filter](#übersicht-filter)
	- [2. Bericht erstellen](#übersicht-bericht)
	- [3. Suche](#übersicht-suche)
	- [4. Sortierung](#übersicht-sortierung)
	- [5. Auswahl](#übersicht-auswahl)
	- [6. Paginierung](#übersicht-paginierung)
- [Detailbereich](#detailbereich)
	- [1. Adresse](#detailbereich-adresse)
	- [2. Zahlungsdetails](#detailbereich-zahlungsdetails)
	- [3. Versanddetails](#detailbereich-versanddetails)
	- [4. Bestätigungen](#detailbereich-bestaetigungen)
	- [5. Aktionsbereich](#detailbereich-aktionsbereich)
	- [6. Stornierung](#detailbereich-stornierung)
	- [7. Aktualisierung](#detailbereich-aktualisierung)
	- [8. Auflistung](#detailbereich-auflistung)
	- [9. Summen](#detailbereich-summen)
	- [10. Revision](#detailbereich-revision)

**Expected behavior**
The Index / Right Sidebar is scrollable independently of the main content.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/36986615/60868485-72841e80-a22d-11e9-9ad6-ca18c5fe5e88.jpg)

**Desktop:**
 - OS: Windows 7
 - Browser: Chrome
 - Version: 75.0.3770.100

**Comment by saleem-hadad** [comment]
Hi @fabianpnke ,
thanks for sharing this issue,
I understand why, just a single CSS line will solve it.
However, you can solve this issue temporarily by adding a new lareciep theme to your project and override the behavior:
```bash
php artisan larecipe:theme vendor-name/custom-theme
```
then put these lines in the provided css file under `larecipe_components` dir.
```css
. documentation > ul:first-of-type {
    overflow: scroll;
}
```

**Comment by cacpmw** [comment]
@saleem-hadad please dont overlook this

**Comment by Dylan-Duault** [comment]
Any news about this ? I have the same issue and adding overflow: scroll; to the first ul doesn't fix anything. @saleem-hadad 

@fabianpnke Did you find a way to fix it ?

Thanks

**Comment by WillGoldstein** [comment]
try adding this to a [custom css](https://larecipe.binarytorch.com.my/docs/2.2/custom-css-and-js):

```
#app > div:nth-child(2) > div.documentation.is-dark > ul:nth-child(3){
    height: calc(100% - 60px);
    overflow-x: hidden;
    overflow-y: auto;
    padding-bottom:80px; /**force scroll bar on large containers **/
    -webkit-overflow-scrolling: touch;
}
```
