### ISSUE TITLE
Add variables to versions

### ISSUE THREAD

**Issue by marcoT89** [saleem-hadad/larecipe#138]
**Is your feature request related to a problem? Please describe.**
It would be very nice to have a way to set some variables to versions to be used like `{{version}}` for example. I use larecipe to create API documentations and I would like to use variables a lot instead of repeating things.

**Describe the solution you'd like**
For example in the `config/larecipe.php`:
```php
"variables" => [
    "default": [
        "support_email": "support@mydomain.com",
    ],
    "1.0": [
        "api_url": env('API_URL') . "/api/v1"
    ],
    "2.0": [
        "api_url": env('API_URL') . "/api/v2"
    ]
],
```
And in the markdown I would use like this:
```markdown
### Endpoints

`{{api_url}}/oauth/token`
```
And it would output something like this: `https://mydomain.com/api/v1/oauth/token`.
This would be really helpfull! 

What do you think? Thanks!

**Comment by saleem-hadad** [comment]
Hi @marcoT89 
I got what you mean but there's no official support from by LaRecipe so far.

I achieved the same functionality using Blade directives a while ago as a quick solution.

In the `AppServiceProvider` add this in the `boot` method:
```php
...
use Illuminate\Support\Facades\Blade;

class AppServiceProvider extends ServiceProvider
{
    public function boot()
    {
         Blade::directive('customVar', function() {
             return 'varValue';
         });
    }
    ...
}
```

Then in your docs: 
```md
The value of customVar is: @customVar
```

**Comment by marcoT89** [comment]
Well... I don't like this solution and I still think this feature is needed... But thanks for the response.

**Comment by saleem-hadad** [comment]
Well, I'll add it to the future work then and hopefully, one day will be available :)

**Comment by mbroadhead** [comment]
@marcoT89 

Here is another solution:
In your config file `config/larecipe.php`:
```php
return [
...
    // put your custom variables under the 'config' key:
    'config' => [
        'default' => [
            'support_email' => 'support@mydomain.com',
        ],
        '1.0' => [
        ],
        '2.0' => [
            'support_email' => 'new-fancy-api-support@mydomain.com',
        ],
    ],
];
```

In the `AppServiceProvider` add this in the `boot` method:
```php
...
use Illuminate\Support\Facades\{Blade, Config};

class AppServiceProvider extends ServiceProvider
{
    ...
    public function boot()
    {
        Blade::directive('apiconfig', function ($expression, $default_value = '') {

            // Removes surrounding quotes from $expression
            $key = substr($expression, 1, strlen($expression) - 2);

            $api_version = request()->version;
            $api_config = config('larecipe.config');
            $value = null;

            if (isset($api_config[$api_version][$key])) {
                $value = $api_config[$api_version][$key];
            }
            else if(isset($api_config['default'][$key])) {
                $value = $api_config['default'][$key];
            }
            else {
                $value = $default_value;
            }

            return $value;
        });
    }
}
```

Usage: `@apiconfig($key, $default)`

Usage in your blade templates:
```
### Support
You can contact support here: @apiconfig('support_email', 'last-resort-default@mydomain.com')
```

The precedence is as follows:

1.  If `config.$version` exists, use it's value
2. If `config.default` exists, use it's value
3. Finally, use the default provided as the second argument to the blade directive
