### ISSUE TITLE
Unable to load fonts

### ISSUE THREAD

**Issue by RayanAhmadani** [saleem-hadad/larecipe#143]
**Describe the bug**
I installed lararecepie in directory inside the server not the default one, example: https://myserver.com/project1/docs
however, I can't get the fonts to be loaded correctly, I always get 
Failed to load resource: the server responded with a status of 404 (Not Found)

http://myserver.com/vendor/binarytorch/larecipe/assets/fonts/fa-brands-400.woff2

Any idea how I can make it read the correct path?

**To Reproduce**
1. Install lararecepie inside any folder, not the main one.
2. open /docs.
3. right click and choose inspect element.
4. navigate to console.

**Expected behavior**
to load fonts correctly.

**Screenshots**
`
![image](https://user-images.githubusercontent.com/9512390/61358280-089df180-a88b-11e9-8cb1-39e1587dd74d.png)
`

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Version 75.0.3770.100 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by josegus** [comment]
![image](https://user-images.githubusercontent.com/13947849/61669468-2a91dc80-acae-11e9-81a2-4d922e6af695.png)
Same here. I wonder why some packages still using root paths for link assets. Most of the time, I use relative path for velopment under /var/www/

**Comment by saleem-hadad** [comment]
what to use then?
normally I use valet and I have no issues
can you share your suggestions?
