### ISSUE TITLE
Nested Routes

### ISSUE THREAD

**Issue by RayanAhmadani** [saleem-hadad/larecipe#144]
**Describe the bug**
I have index.md which include files that are inside custom directory, however, I can get them to work on the route, for example I have (in index.md):
## Controllers
    - [LoginController](logincontroller)

## Models
    - [ExportNotionalVolume](exports/backoffice/exportnotionalvolume)

When the user navigates to Models, then clicks LoginController, the page becomes 404 not found, example of the domain links

## Controllers
http://myserver.com/myproject/docs/logincontroller

##Models
http://myserver.com/myproject/docs/exports/backoffice/exportnotionalvolume

**To Reproduce**
1. Create route in index.md [LoginController](logincontroller) and [ExportNotionalVolume](exports/backoffice/exportnotionalvolume)
2. Click on [ExportNotionalVolume]
3. Click on [LoginController]
4. See error Not Found

**Expected behavior**
It is expected to be able to switch between Controllers and Models

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 75.0.3770.100 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by RayanAhmadani** [comment]
@saleem-hadad I managed to get this running, just confirm to me if it is a bug so I can create a pull request for it.

**Comment by saleem-hadad** [comment]
Hi @RayanAhmadani 
No, actually it's not a bug, already implemented a long time ago.
Thanks for the gesture
