### ISSUE TITLE
Algolia search

### ISSUE THREAD

**Issue by asivaneswaran** [saleem-hadad/larecipe#148]
Hey,

I enabled algolia, I create a new index and all.

Do I need to run a command to import automatically or do I need to import the data manually?

**Comment by saleem-hadad** [comment]
No, this is no command to run.
Actually, I've no experience setting up a private search on Algolia but if your project is open-source you have to submit your site to get the index.
I think it's better to reach out Algolia for this matter.
Thanks

**Comment by Machecek** [comment]
@asivaneswaran did you have any resolution for this issue?
