### ISSUE TITLE
stop sending me emails pls

### ISSUE THREAD

**Issue by imlinus** [saleem-hadad/larecipe#151]
Yeah, kind of weird getting emails about some random repo, pls stahp

**Comment by saleem-hadad** [comment]
Sorry For Disturb, I just collected a few Laravel developers from GitHub and send this email.

will stop that for sure, sorry again.

**Comment by saleem-hadad** [comment]
so sorry, guys if I bothered you.
This email has been stopped now and you will not receive further emails from me unless you subscribe manually.

**Comment by lorey** [comment]
This is unprofessional beyond measure...
