### ISSUE TITLE
This project sends SPAM via email

### ISSUE THREAD

**Issue by frenck** [saleem-hadad/larecipe#152]
I've just received unsolicited email from this project on my personal email address.

This project should be ashamed of itself to use this type of methods, this is not worthy of any open source project on GitHub.

![image](https://user-images.githubusercontent.com/195327/62629325-3a0b5980-b92d-11e9-9422-11af7fcff654.png)

**Comment by saleem-hadad** [comment]
Sorry dear @frenck,
I sent this email yesterday for a few Laravel developers that I searched for on Github and now stopped, you'll never receive any future email from me, all collected emails have been deleted as well.

**Comment by rogermlml** [comment]
Thank a lot for the response and the speed, I recently started with the laravel world but it is amazing the community. You're right, i don't remember about vendor folder XD. 
Thanks again;
