### ISSUE TITLE
Links going to 1.0.0.0/{page}

### ISSUE THREAD

**Issue by scsddeputy** [saleem-hadad/larecipe#153]
**Describe the bug**
When setting the config 'docs.route' to either '/' or empty '', the routes on the sidebar get set to 1.0.0.0/{page}

**To Reproduce**
1. Install package
2. Set 'docs.route' config setting to either '' or '/'
3. Go to docs 
4. Click link in sidebar and get redirected to http://1.0.0.0/overview

**Expected behavior**
Should go to correct page

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome & Brave Browser
 - Version 76.0.3809.100

**Comment by scsddeputy** [comment]
Looks like it could be an issue with the index.md file created by default.

In index.md when it is created it contains 
```
- ## Get Started
    - [Overview](/{{route}}/{{version}}/overview)
```

I deleted the `{{route}}/` and it seems to have fixed the bug

**Comment by saleem-hadad** [comment]
thanks @scsddeputy glad the issue now solved
