### ISSUE TITLE
How to modify the default layout file?

### ISSUE THREAD

**Issue by ilongley** [saleem-hadad/larecipe#156]
It appears only the partials are published to the Laravel views folder, however I would like to modify the master layout file.

Do I need to do this in the core vendor package, or is there another way to go about this that I'm missing?

Many thanks.

**Comment by arxeiss** [comment]
You can just copy `vendor/binarytorch/larecipe/resources/views/default.blade.php` into `resources/views/vendor/larecipe/default.blade.php` and it will work :)

This way you can override every view, even those which are not published. This is basic Laravel thing. Nothing magical.
