### ISSUE TITLE
Use for local environment only

### ISSUE THREAD

**Issue by dataffinityhealth** [saleem-hadad/larecipe#159]
**Is your feature request related to a problem? Please describe.**

When installing I would like a way to set a config or register the service provider for when the sit is local only. We would use these docs for local development to help new developers understand our business logic and some of the choices we made.

**Describe the solution you'd like**

Similar to Larval Telescope where you can register the service provider for local development environment.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by saleem-hadad** [comment]
Added to future development list #6

**Comment by saleem-hadad** [comment]
This is removed from the roadmap. You can use Laravel gate for that.
https://larecipe.binarytorch.com.my/docs/2.0/authorization
