### ISSUE TITLE
Typo in vue-components-support docs

### ISSUE THREAD

**Issue by uonick** [saleem-hadad/larecipe#16]
**To Reproduce**
1. Go to 'https://larecipe.binarytorch.com.my/docs/1.0/vue-components-support'
2. See:
<img width="1159" alt="screen shot 2018-09-11 at 01 08 15" src="https://user-images.githubusercontent.com/365029/45321602-3590c200-b55f-11e8-9d49-50318f8b977b.png">

**Comment by saleem-hadad** [comment]
Thank you @uonick for your contribution.
I've fixed it now and published all the docs as well in another repo: https://github.com/saleem-hadad/larecipe-docs
You're welcome to contribute anywhere
