### ISSUE TITLE
Generate static files

### ISSUE THREAD

**Issue by Sh1d0w** [saleem-hadad/larecipe#17]
**Is your feature request related to a problem? Please describe.**
Larecipe has really nice UI and it is very easy to use. Thus I would like to use it for documenting a lot of my FOSS projects which do not use Laravel.

**Describe the solution you'd like**
We need a command that will generate static html files in the public folder that then can be easily copied or deployed to a domain without the need of Laravel (like S3 bucket or Github Pages).

**Comment by saleem-hadad** [comment]
Hello @Sh1d0w 
Thank you for your suggestion, actually, we thought about this feature before but not within Laravel itself, I mean similar to Vuepress. I'll discuss this issue with my team and we'll see if we can manage to do it once we are free.
However, If you or anyone is interested in implementing this feature would be awesome.
