### ISSUE TITLE
Not getting most up to date version from composer

### ISSUE THREAD

**Issue by WillGoldstein** [saleem-hadad/larecipe#171]
**Describe the bug**
After deleting my `vendor/binarytorch/larecipe` folder, running `composer clear-cache`, and then making sure my `composer.json` file has `"binarytorch/larecipe": "~2.2",`, I then run `composer install` and larecipe gets installed, but I know it's out of date because this file:

`vendor/binarytorch/larecipe/resources/views/default.blade.php`

has 
```
		<!-- Base url -->
		<base href="{{ Config::get('app.url') }}/" />
```
which was removed with #167 .

**Expected behavior**
Up to date files get downloaded from composer.

**Comment by WillGoldstein** [comment]
Also noticing my changes from #163  are not included.

**Comment by WillGoldstein** [comment]
It would appear as though https://packagist.org/packages/binarytorch/larecipe#v2.2.0 is stale:
![image](https://user-images.githubusercontent.com/20759342/65642577-a285c700-dfbd-11e9-9dab-d267c3cea46d.png)

**Comment by kamicloud** [comment]
You can use dev-master instead until next release

**Comment by AbbyJanke** [comment]
I noticed this as well, there's some other PRs not in there. Guessing that @saleem-hadad doesn't have auto-update for packagist setup.

**Comment by saleem-hadad** [comment]
This update will be available in the next version 2.3, not released yet

**Comment by WillGoldstein** [comment]
@saleem-hadad do you know when we can expect that release? My prod app launching in the next week or so is very dependent on all these fixes/updates such as #163.

**Comment by saleem-hadad** [comment]
Yes, this weekend I'll release the new version

**Comment by WillGoldstein** [comment]
Oh, that’s so awesome and fantastic news, thanks so much @saleem-hadad ! This library rocks

**Comment by saleem-hadad** [comment]
Most welcome :D 😍
