### ISSUE TITLE
The right menu does not scroll when there is too much content

### ISSUE THREAD

**Issue by gedongdong** [saleem-hadad/larecipe#172]
**Describe the bug**
The right menu does not scroll when there is too much content.I can't see the full right side menu, which is not very friendly to small screen computers.The package version is 2.2.

**Screenshots**
![image](https://user-images.githubusercontent.com/13677866/65954345-63052200-e478-11e9-85f5-9c4919773d76.png)

![image](https://user-images.githubusercontent.com/13677866/65954069-e07c6280-e477-11e9-863f-ae93d15b1f1b.png)

**Desktop (please complete the following information):**
 - OS: [macOS 10.14]
 - Browser [chrome]
 - Version [the newest]

**Comment by saleem-hadad** [comment]
I think this is not a common issue and can be solved easily by [custom css](https://larecipe.binarytorch.com.my/docs/2.0/custom-css-and-js)

**Comment by WillGoldstein** [comment]
@saleem-hadad I  would actually argue that this is too easily common and a big issue if you have too many items or the users monitor is garbage. I just ran into it myself and fixed it. Anyway, here's the solution @gedongdong :

as @saleem-hadad said, follow his awesome custom css instructions. Then, in `larecipe-components/YOURTHEME/resources/css/theme.css` add this:

```
#app > div:nth-child(2) > div.documentation.is-dark > ul:nth-child(3){
    height: calc(100% - 60px);
    overflow-x: hidden;
    overflow-y: auto;
    padding-bottom:80px; /**force scroll bar on large containers **/
    -webkit-overflow-scrolling: touch;
}
```

Maybe I'll make a PR for this to be in the shipped css?
