### ISSUE TITLE
Anchor links not working as expected

### ISSUE THREAD

**Issue by da3monHunter** [saleem-hadad/larecipe#173]
**Describe the bug**
```
- [Example](#example-link)

<a name="example-link">
## Example
```
is directing to `base_url/#example-link` rather then `base_url/segment1/segment2#example-link` when the page url is `base_url/segment1/segment2`

**To Reproduce**
Current URI = `http://localhost:8000/docs/1.0/overview`
```
# Overview

---

- [Introduction](#introduction)
- [Test](#test)

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<a name="introduction"></a>

##  Introduction
```
on anchor click the uri changes to `http://localhost:8000/#introduction` 

**Expected behavior**
The uri should become `http://localhost:8000/docs/1.0/overview#introduction`

**Additional context**
To Achieve the expected result i have to do: `- [Introduction](/{{route}}/{{version}}/overview/#introduction)` which doesn't seem right to do.

"laravel/framework": "^6.0",
 "binarytorch/larecipe": "^2.2",

**Comment by aFluxx** [comment]
Has this PR been merged. I seem to run into the same problem. 


Version:  `"binarytorch/larecipe": "^2.2"`

**Comment by intellow** [comment]
I'm seeing the same problem as well. Would love to see the PR merged.

**Comment by WillGoldstein** [comment]
Wasn’t this merged @intellow ?

**Comment by intellow** [comment]
> Wasn’t this merged @intellow ?

PR is still open. Also, there hasn't been a release since Sep 12. Even if this was merged, it hasn't been released so unless you are pulling in dev-master to your project, you wouldn't see the fix.

**Comment by WillGoldstein** [comment]
Oh sorry, you're right - I was looking on mobile and thought this was regarding a different PR.

**Comment by Felo-Z** [comment]
I have the same question.

**Comment by dbfx** [comment]
+1

**Comment by classiebit** [comment]
Same issue here as well, our docs are running in production -

- [https://anofie-docs.classiebit.com/docs/1.0/introduction](https://anofie-docs.classiebit.com/docs/1.0/introduction)
- [https://eventmie-docs.classiebit.com/docs/1.0/introduction](https://eventmie-docs.classiebit.com/docs/1.0/introduction)


Please resolve the issue ASAP. Although we love LaRecipe so much.

Thank you

**Comment by intellow** [comment]
While obviously not ideal, as a workaround I removed any of my anchor links and replaced it with a link to my homepage. That way until this is fixed my site doesn't seem to be "broken" for the users.

**Comment by WillGoldstein** [comment]
@da3monHunter @intellow @classiebit @dbfx @Felo-Z @aFluxx  (why is there not an @here @github?! 🙄 🤣)

Ah, I see why I don't notice this issue anymore. Here's a simple and reliable fix you can do whilst you wait for the PR to be merged:

Copy 

`vendor/binarytorch/larecipe/resources/views/default.blade.php`

to your resources folder so you have:

`resources/views/vendor/larecipe/default.blade.php`

Then add 

```
		<!-- Base url -->
		<base href="{{ Config::get('app.url') }}/" />
```

After line 48, or right after this code:

```
        @foreach(LaRecipe::allStyles() as $name => $path)
            <link rel="stylesheet" href="{{ route('larecipe.styles', $name) }}">
        @endforeach
```

That fixed it for me right gud.

**Comment by Felo-Z** [comment]
@WillGoldstein It worked!

**Comment by classiebit** [comment]
@WillGoldstein awesome. Thank you.

**Comment by saleem-hadad** [comment]
sorry guys for being late helping you out
I just released a new version 2.2.1
please confirm the fix

**Comment by da3monHunter** [comment]
fixed thanks <3

**Comment by jadamec** [comment]
How to add an external link, please? It's still giving me the prefix url... Thanks!
