### ISSUE TITLE
Authorization not working

### ISSUE THREAD

**Issue by sportuondo** [saleem-hadad/larecipe#175]
I'm using the 2.2.0 version and whenever I define a Gate, the system returns a 403 Forbidden page.

In `App/Providers/AuthServiceProvider`:

```php
public function boot()
{
    $this->registerPolicies();

    Gate::define('viewLarecipe', function($user, $documentation) {
        return true;
    });
}
````

Captured Gate response:

```php
[
  "ability" => "viewLarecipe"
  "result" => null
  "user" => null
  "arguments" => "[0 => Object(BinaryTorch\LaRecipe\DocumentationRepository)]"
]
```

Any ideas? Thank you!

**Comment by WillGoldstein** [comment]
Can I see your config file?

**Comment by sportuondo** [comment]
Your question has put me on track to realize that I needed to force update the config file with `php artisan vendor:publish --tag=larecipe_config --force` which adds the `'middleware' => ['web']` param.

Sorry for bothering you and thank you for your work!
