### ISSUE TITLE
PHP code being rendered in documentation

### ISSUE THREAD

**Issue by tnylea** [saleem-hadad/larecipe#177]
**Describe the bug**
When adding any blade directives inside of code blocks for my documentation, Larecipe tries to execute those code blocks as actual PHP code. If there is an undefined variable in the docs or a syntax error, the page will throw an error.

**To Reproduce**
1. Add a blade directive such as `@if` to your .md file
2. Try and view that documentation, you will get an error

**Expected behavior**
Expected Behavior would be to see the documentation file, but instead I get an error

**Screenshots**
![Screen Shot 2019-11-03 at 12 35 54 PM](https://user-images.githubusercontent.com/601261/68091594-808e2880-fe36-11e9-88a5-bea98fcb6fed.png)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.4
 - Browser CHROME
 - Version 77.03

**Additional context**
I just upgraded to the latest version of Larecipe and this is happening now, it was not happening when I was using version 1.0.

If anyone could help me figure this out, I would really appreciate it :) Thanks!

**Comment by WillGoldstein** [comment]
It’d be a nice to have but I wouldn’t say it’s a bug necessarily. Why are you needing to use blade syntax in markdown? Have you tried making your own vue component instead?

**Comment by telkins** [comment]
I'm not sure if this is related, but I'd like to pass in variables, so that I can use the same value across all my docs and quickly/easily change it if/when it's needed.

Is this possible...?

**Comment by telkins** [comment]
Of course, it may be that I'm looking for this: https://github.com/saleem-hadad/larecipe/issues/138

**Comment by WillGoldstein** [comment]
Gotchya, makes sense. Seems like that issue you referenced has a solution?

**Comment by telkins** [comment]
@WillGoldstein Well, it does provide a solution, but not one that I or at least one of the others here are terribly happy with.  :-/

**Comment by WillGoldstein** [comment]
@telkins indeed, perhaps I should have said “workaround” instead of “solution”

**Comment by saleem-hadad** [comment]
as for now, this issue fixed in v2.4.3
![Screen Shot 2020-09-09 at 12 20 15 AM](https://user-images.githubusercontent.com/12780866/92523941-49488f00-f232-11ea-9868-c46f605d38b8.png)
