### ISSUE TITLE
Help us Saleem, you're our only hope

### ISSUE THREAD

**Issue by WillGoldstein** [saleem-hadad/larecipe#179]
Help us @saleem-hadad , we need you!

There are a number of PRs which were merged after the most recent date shown in [packagist](https://packagist.org/packages/binarytorch/larecipe#v2.2.0). Would it be possible for you to please update this?

Also, while a different repo but very related, the docs for larecipe are [stale](https://github.com/saleem-hadad/larecipe-docs/issues/9).

![image](https://user-images.githubusercontent.com/20759342/68306459-99d1e780-0077-11ea-9b80-663390c78484.png)

**Comment by saleem-hadad** [comment]
hahah 😂that made my day
Sorry for being inactive lately, I just got married and a job in Dubai, so yeah a lot of changes.

**Comment by WillGoldstein** [comment]
Lol glad you liked it and no problem. Congrats 🎊🍾🎉 @saleem-hadad !!!

**Comment by saleem-hadad** [comment]
Thank you @WillGoldstein 🌹
