### ISSUE TITLE
Problems with TOC (Table Of Content)

### ISSUE THREAD

**Issue by marcodevsquad** [saleem-hadad/larecipe#180]
**Describe the bug**
The suggested markdown to generate a navigatable title in table of contents is not working.

**To Reproduce**
```markdown
- [Example](#example-link)

<a name="example-link">
## Example
```

**Expected behavior**
Generate a link like this:
![image](https://user-images.githubusercontent.com/30419576/68597913-8ad6a500-047c-11ea-9ee3-ac1f576fe84f.png)

BUT, it is generating this:
![image](https://user-images.githubusercontent.com/30419576/68598137-fb7dc180-047c-11ea-8b6e-4a35885de4c3.png)

Did I miss something?

**Comment by tpaksu** [comment]
Found out what's missing, the code in documentation doesn't contain the link on the H2.

```markdown
- [Example](#example-link)

<a name="example-link">
## Example
```

should be

```markdown
- [Example](#example-link)

<a name="example-link">
## [Example](#example-link)
```

**Comment by saleem-hadad** [comment]
Thank you @tpaksu for the correction, I've updated the docs now

**Comment by tpaksu** [comment]
@saleem-hadad You're welcome. Thank you for creating this package!
