### ISSUE TITLE
Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by hedeqiang** [saleem-hadad/larecipe#186]
larecipe versions : * v2.2.1
php： php7.4

laravel : 5.8
This stopped working on php 7.4

![image](https://user-images.githubusercontent.com/31909061/69895138-2d3fc500-1365-11ea-81b1-d1af1b38c785.png)

**Comment by hedeqiang** [comment]
https://github.com/erusev/parsedown-extra/pull/135

**Comment by cacpmw** [comment]
@hedeqiang how to solve this? I required the erusev package directly on my composer.json and still didnt fix it.

**Comment by hedeqiang** [comment]
@cacpmw   reference this pr https://github.com/erusev/parsedown-extra/pull/135

It seems to be fixed ,But the merge haven't been done yet.

**Comment by coding-sunshine** [comment]
that repo erusev/parsedown-extra#135 doesn't seem like its being maintained anymore. :(

**Comment by cacpmw** [comment]
@coding-sunshine you have to see what they've changed and then go to your vendors folder and edit the package yourself. I know that is not advisable but it seemed to be the only solution for me

**Comment by coding-sunshine** [comment]
@cacpmw yes, I did the same for now as it was just oneliner but definitely not advisable. Can something be done in larecipe package to fix this?

**Comment by WillGoldstein** [comment]
I believe we can fix this by editing the `composer.json` file:

```
    "require": {
        "php": ">=7.1.3",
        "illuminate/support": "~5.4.0|~5.5.0|~5.6.0|~5.7.0|~5.8.0|^6.0",
        "illuminate/view": "~5.4.0|~5.5.0|~5.6.0|~5.7.0|~5.8.0|^6.0",
        "erusev/parsedown-extra": "^0.8.0",   // To newest version
        "symfony/dom-crawler": "^4.1"
    },
```

**Comment by Bcryp7** [comment]
Encounter same issue, is there a reason why the composer.json is not being merge yet with the latest parsedown-extra version?

**Comment by derweba** [comment]
Is there already a fix? I am facing the same problem.

**Comment by WillGoldstein** [comment]
Yes @derweba pr #189

**Comment by saleem-hadad** [comment]
thank you guys ❤️
