### ISSUE TITLE
Overview page on existing project white screen

### ISSUE THREAD

**Issue by rymesaint** [saleem-hadad/larecipe#187]
I got white screen when i installed larecipe with existing project. i didn't find any error on console, after i find the problem because this code `:class="{'expanded': ! sidebar}"` when i try to remove it the page content is being displayed but the sidebar is not displayed.

Could you help me

**Comment by saleem-hadad** [comment]
did you run this command?
```
php artisan larecipe:install
```

**Comment by rymesaint** [comment]
yes, i did run the command

**Comment by saleem-hadad** [comment]
is this still open? did you solve it?

**Comment by rymesaint** [comment]
> is this still open? did you solve it?

still could not solve it

**Comment by saleem-hadad** [comment]
please update to the latest version and try to force publishing the assets needed

```
php artisan vendor:publish --tag=larecipe_assets --force
```
