### ISSUE TITLE
missing MD's?

### ISSUE THREAD

**Issue by jayenne** [saleem-hadad/larecipe#188]
**Describe the bug**
I can't seem to create new paragraphs or a simple blockquote
typically, I would have expected a double-space to instert a <br/> tag; a double-linebreak to create a new paragraph; and > to inster a block quote. no seem to be doing the trick.

Is this by design or have i missed something?

**To Reproduce**

create a page
write a line of blurb
add  a double space to insert a <br/>
write some more blurb
add two linebreaks 
write some more blurb
prefix last blub with >
notice that none of the three tags had any effect.

**Expected behavior**
A forced line break, a new paragraph and a blockquote on the last line of blurb.

*I've not tested all the standard MD tags to see if any others aren't there.

**Comment by WillGoldstein** [comment]
Yeah @jayenne, I've seen that too. I often use a line break (not `<br>` but just enter on keyboard) followed by `<div></div>`, so:

```
>{primary.fa-alert} some warning yay!

<div></div>
![](/img/src/assets/yay.jpg)
```

which would get the image outside of that alert box.
