### ISSUE TITLE
General workflow for managing documentation

### ISSUE THREAD

**Issue by LarryBarker** [saleem-hadad/larecipe#192]
**Is your feature request related to a problem? Please describe.**
This is just a general question

**Describe the solution you'd like**
I'm trying to better understand how to manage documentation through version control in production environments. This also relates to an editor being available to make it easy for content managers to edit documentation with a visual editor.

**Describe alternatives you've considered**
Storing documentation content in a database.

**Additional context**
I implemented a visual markdown editor which generates the markdown files; however, this is problematic because changes are made to files on the production server, which are overwritten with new deployments. Obviously I can add the docs folder to .gitignore, but we lose version control in doing so. The general problem is how to push changes from the production environment back down to the remote repo. This is also a problem for CMS systems that use file based content storage vs database storage. 

I'm just curious how others are handling this problem in general. Thanks for a great package and any feedback!

**Comment by WillGoldstein** [comment]
This solution isn't designed to be inputted a la CMS style. Nothing out of the box (that I know of) is set up for that - you need to update the files directly.

Lots of good functionality for gatekeeping/corralling users to only certain versions or pages though.

**Comment by LarBearrr** [comment]
Hi @WillGoldstein, thanks for the reply. I understand there is no visual editor included; I've implemented my own version. I also know docs can be "gated."

I'm more interested in how we go about version controlling docs that have been created/updated/removed from a production environment. I understand this is not inherently a question related to the package, but I have been unable to find any good references elsewhere so I thought I would see what people who are using LaRecipe are doing to manage their docs in production environments.

**Comment by WillGoldstein** [comment]
Can’t you just put a version behind a gate? That’s what I do.

**Comment by WillGoldstein** [comment]
@LarBearrr sorry my replies last night were sent whilst I sat down to watch Star Wars in theaters for the first time (late to the showing).

Looking into this further, I do think that you will want to try to take advantage of example 4 [here](https://larecipe.binarytorch.com.my/docs/2.2/authorization) (also you will probably want to read [this](https://larecipe.binarytorch.com.my/docs/2.2/configurations#settings).

You can access `$documentation->version` in the Gate to determine, based on the user, whether or not you should show it.

I believe this can be closed as the functionality exists?

**Comment by saleem-hadad** [comment]
You can host your docs in another repo and then make git pull from your main repo as a sub-repo under resources/docs but this is a bit complex to handle.
For now, there's no official support for UI editor yet. However, it's coming in LaRecipe V3.
