### ISSUE TITLE
GitHub Icon Link

### ISSUE THREAD

**Issue by rogermlml** [saleem-hadad/larecipe#193]
My question is if it's possible to change the GitHub link in the icon next to the version docs.
I can't see the option in config file.

**Comment by WillGoldstein** [comment]
Remember, this is Laravel, so you can easily do anything you want to the blades in `resources/views/vendor/larecipe`. Specofically, and this is how I solved this, go to `resources/views/vendor/larecipe/partials/nav.blade.php` and comment out the github icon you are referring to like so:

```
            {{--<larecipe-button tag="a" href="https://github.com/saleem-hadad/larecipe" target="__blank" type="black" class="mx-2 px-4">
                <i class="fab fa-github"></i>
            </larecipe-button>--}}
```

I think it may be around line 38, but I may have adjusted my file some and my lines may differ from stock.

This can be closed.

**Comment by rogermlml** [comment]
Thank a lot for the response and the speed, I recently started with the laravel world but it is amazing the community. You're right, i don't remember about vendor folder XD.
Thanks again;

**Comment by WillGoldstein** [comment]
> You're right, i don't remember about vendor folder XD.

Stay away from the vendor folder!! Remember, only edit blades in the **resources** folder, or else you will lose all your work.

No prob, and enjoy using this repo - I know I did/do!

**Comment by WillGoldstein** [comment]
@rogermlml I hope you got that last comm - since you closed the issue, I don't know if you'll see it w/o my tagging you directly, but it's important.
![image](https://user-images.githubusercontent.com/20759342/73028453-8ecf5d80-3e03-11ea-81c3-705b21315d21.png)

**Comment by rogermlml** [comment]
yeah... I closed it much faster... so i achieve to do the GitHub link but now I need to style a little bit the search div when search icon is clicked but in blades, components are uploaded and I only find them on vendors folder...

I know that vendor folder aren't project files but how can I modify the style of a component if there is where are they stored?

**Comment by derweba** [comment]
Stumbling across this issue by accident, and maybe i can help you.

If you look under `resources/views/vendor/larecipe` there are parts of larecipe defined. (Like specified in the [documentation](https://larecipe.binarytorch.com.my/docs/2.2/custom-views) ).

If you want to override other larecipe views just simply copy (or add new) files corresponding to the `vendor\binarytorch\larecipe\resources\views` folder. (Again, don't change anything in there) Laravel will first search in your own resource folder if the view exists in there and then looks for the view in the vendor folder.

So for example if you want to define your own `docs` view copy the `docs.blade.php` from `vendor\binarytorch\larecipe\resources\views` to `resources/views/vendor/larecipe` and change whatever you want in there.

@WillGoldstein why is the folder in project resources called vendor? Isn't this a bit missleading? Or is this convention, i don't know... i'm for myselfe quiet new tho Laravel.

**Comment by rogermlml** [comment]
Thanks derweba! but i don't want to override a view. I only want to change the font-size of one component in NavigationBar. I can change the different divs inside this view and also i can't add new tags but i can't change style of the component that upload when you click the search button!

**Comment by derweba** [comment]
Have you seen [this](https://larecipe.binarytorch.com.my/docs/2.2/custom-css-and-js)? Here you can add your own css an js.

**Comment by WillGoldstein** [comment]
@derweba i believe that’s consistent with laravel, yes.
