### ISSUE TITLE
bdd Code

### ISSUE THREAD

**Issue by dschiller** [saleem-hadad/larecipe#204]
```
'''bdd
Feature: My Feature
     Scenario: A Scenario
'''
```

Results in `app.js:1 GET https://cdnjs.cloudflare.com/ajax/libs/prism/1.15.0/components/prism-text.min.js net::ERR_ABORTED 404`

**Comment by saleem-hadad** [comment]
unfortunately, no support for bdd at this moment. You're welcome to propose a PR for a fix
