### ISSUE TITLE
Install Issue "erusev/parsedown 1.7.3"

### ISSUE THREAD

**Issue by RichieMcMullen** [saleem-hadad/larecipe#207]
Problem 1
    - Conclusion: don't install binarytorch/larecipe v2.3.0
    - Conclusion: remove erusev/parsedown 1.7.3
    - Installation request for binarytorch/larecipe ^2.3 -> satisfiable by binarytorch/larecipe[2.x-dev, v2.3.0].
    - Conclusion: don't install erusev/parsedown 1.7.3
    - binarytorch/larecipe 2.x-dev requires erusev/parsedown-extra ^0.8.1 -> satisfiable by erusev/parsedown-extra[0.8.1, 0.8.x-dev].
    - erusev/parsedown-extra 0.8.1 requires erusev/parsedown ^1.7.4 -> satisfiable by erusev/parsedown[1.7.4, 1.7.x-dev, 1.8.0-beta-1, 1.8.0-beta-2, 1.8.0-beta-3, 1.8.0-beta-4, 1.8.0-beta-5, 1.8.0-beta-7, v1.8.0-beta-6].
    - erusev/parsedown-extra 0.8.x-dev requires erusev/parsedown ^1.7.4 -> satisfiable by erusev/parsedown[1.7.4, 1.7.x-dev, 1.8.0-beta-1, 1.8.0-beta-2, 1.8.0-beta-3, 1.8.0-beta-4, 1.8.0-beta-5, 1.8.0-beta-7, v1.8.0-beta-6].
    - Can only install one of: erusev/parsedown[1.7.4, 1.7.3].
    - Can only install one of: erusev/parsedown[1.7.x-dev, 1.7.3].
    - Can only install one of: erusev/parsedown[1.8.0-beta-1, 1.7.3].
    - Can only install one of: erusev/parsedown[1.8.0-beta-2, 1.7.3].
    - Can only install one of: erusev/parsedown[1.8.0-beta-3, 1.7.3].
    - Can only install one of: erusev/parsedown[1.8.0-beta-4, 1.7.3].
    - Can only install one of: erusev/parsedown[1.8.0-beta-5, 1.7.3].
    - Can only install one of: erusev/parsedown[1.8.0-beta-7, 1.7.3].
    - Can only install one of: erusev/parsedown[v1.8.0-beta-6, 1.7.3].
    - Installation request for erusev/parsedown (locked at 1.7.3) -> satisfiable by erusev/parsedown[1.7.3].

**Comment by stygiansabyss** [comment]
Laravel framework itself uses 1.7.  So yeah, it will throw this error.

**Comment by stygiansabyss** [comment]
For my case, this solved it:

Use one or the other for erusev.  Whichever works for you.
```
composer require erusev/parsedown:^1.7
composer update erusev/parsedown
composer require binarytorch/larecipe
```
