### ISSUE TITLE
Missing Prism-Text Asset

### ISSUE THREAD

**Issue by RichieMcMullen** [saleem-hadad/larecipe#209]
Just noticed a missing asset within chrome inspector. The CDN link is no longer available.

`GET https://cdnjs.cloudflare.com/ajax/libs/prism/1.15.0/components/prism-text.min.js net::ERR_ABORTED 404`

**Comment by saleem-hadad** [comment]
please don't use 
\```text 
your text here
\```

just use 

\```
your text here
\```

**Comment by saleem-hadad** [comment]
or ```json
