### ISSUE TITLE
The version number in the dropdown is wrong when setting route to '/'

### ISSUE THREAD

**Issue by mattias-persson** [saleem-hadad/larecipe#21]
**Describe the bug**
When setting up the package with route set to '/', the version numbers in the dropdown to the right in the header have the wrong URL. For example, version 1.0 leads to //1.0, while version 1.1 leads to //1.1.

**To Reproduce**
1. Install the package. Set the docs.route configuration to '/'.
2. Click on the version dropdown in the top right.
3. End up on something like https://1.0.0.0/1.0

**Expected behavior**
The correct base url should be used.

**Screenshots**
<img width="416" alt="skarmavbild 2018-09-13 kl 11 06 02" src="https://user-images.githubusercontent.com/34786113/45478797-0cca2180-b745-11e8-9c45-cbf1a53387e8.png">

**Desktop (please complete the following information):**
 - OS: macOS High Sierra 10.13.6
 - Browser: Chrome 
 - Version 69.0.3497.92

**Comment by mattias-persson** [comment]
Ah, thanks. The workaround works, that's fine with me for now!

**Comment by saleem-hadad** [comment]
Cool 🤩
