### ISSUE TITLE
when trying to show blade code in .md file in attempts to render it

### ISSUE THREAD

**Issue by waw3** [saleem-hadad/larecipe#210]
`ParseError: syntax error, unexpected ',' in vendor/binarytorch/larecipe/src/Traits/HasBladeParser.php(27) : eval()'d code:29 Stack trace: #0 vendor/binarytorch/larecipe/src/Models/Documentation.php(80): BinaryTorch\LaRecipe\Models\Documentation->renderBlade('<h1>FAQ</h1>\n<h...', Array) #1 `

using v2.3.0

code im using:

```php
@php
    $current_post = Theme::get('current_post');
@endphp
```

**Comment by saleem-hadad** [comment]
fixed now in v2.4.3
