### ISSUE TITLE
Markdown Line Breaks and Blockquotes not working properly

### ISSUE THREAD

**Issue by dschiller** [saleem-hadad/larecipe#211]
**Describe the bug**
When using Markdown Code like:

```
### My Topic

Some Information.

#### A Sub Topic

With Informations.

> A Blockquote...
```

This results in:

![image](https://user-images.githubusercontent.com/3144986/78750967-98cc1b80-7971-11ea-8865-e12b27d2e2a2.png)

But the expected Behaviour is something like this ( Created with ``https://stackedit.io`` ):

![image](https://user-images.githubusercontent.com/3144986/78751057-cdd86e00-7971-11ea-8e10-892ed3a7af61.png)

**To Reproduce**
1. Create a new ``md`` File
2. Add the Content
```
### My Topic

Some Information.

#### A Sub Topic

With Informations.

> A Blockquote...
```
3. Save the File
4. Open the Site in Larecipe
4. See the wrong Visualization of the Markdown Code

**Expected behavior**
![image](https://user-images.githubusercontent.com/3144986/78751212-11cb7300-7972-11ea-8ff3-90c3a4cfa2cc.png)

**Screenshots**
Actual Behaviour:
![image](https://user-images.githubusercontent.com/3144986/78751238-1d1e9e80-7972-11ea-989d-1029bf7a4790.png)

Expected Behaviour:
![image](https://user-images.githubusercontent.com/3144986/78751254-23ad1600-7972-11ea-95f0-bd73bd68e7e8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 2.3.0

**Additional context**
Where can I find the Markdown Parser in Larecipe. I can fix it then.

**Comment by saleem-hadad** [comment]
blockquote in LaRecipe is a bit different you have to include the type of it in order to work:
```
>{info} a blockquote
```
