### ISSUE TITLE
Is there a way to show Line Numbers in Code Blocks ?

### ISSUE THREAD

**Issue by dschiller** [saleem-hadad/larecipe#212]
**Is your feature request related to a problem? Please describe.**
In a Code Block like:
```
` ` ` python
def class():
   pass

   def method(self):
      pass
` ` `
```
I would like to have Line Numbers to be able to point to Line Numbers.

**Describe the solution you'd like**
Show Line Numbers on the left side of Code Blocks.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by dschiller** [comment]
I found a Workaround:
```
` ` ` python
1   def class():
2      pass
3   
4      def method(self):
5         pass
` ` `
Which Results in:
![image](https://user-images.githubusercontent.com/3144986/78773371-69c6a180-7993-11ea-9f80-4ba038fbc960.png)

**Comment by dschiller** [comment]
There is something I found for Prism: `https://prismjs.com/plugins/line-numbers`
But how can I add a class to the `pre` Markdown ?

```
` ` ` python, class=line-numbers
` ` `
```

**Comment by dschiller** [comment]
There is one possible Solution to implement a new Asset in Larecipe with this Code: `https://codepen.io/heiswayi/pen/jyKYyg` but unfortunetly in Larecipie 2.3.0 it is not possible to create new Assets / Tools ( see `https://github.com/saleem-hadad/larecipe/issues/213` )

**Comment by dschiller** [comment]
Is this Project still alive ?

**Comment by saleem-hadad** [comment]
you can do the following:

```php.line-numbers
// your code here
```

![Screen Shot 2020-09-08 at 11 25 12 PM](https://user-images.githubusercontent.com/12780866/92519167-9294e080-f22a-11ea-861d-e5fc7eec55bd.png)

**Comment by dschiller** [comment]
Thank's a lot! Lovely! Where can I find the Documentation for that ?
