### ISSUE TITLE
Uncaught TypeError: LaRecipe.booting(...) is not a function

### ISSUE THREAD

**Issue by dschiller** [saleem-hadad/larecipe#213]
**Describe the bug**
Folow these Steps: `https://larecipe.binarytorch.com.my/docs/2.2/custom-css-and-js#new-tool-or-asset`
Results in Console Error in Browser:
![image](https://user-images.githubusercontent.com/3144986/78776075-9381c780-7997-11ea-9fdd-4078b98fbfb1.png)

**To Reproduce**
1. Go to 'https://larecipe.binarytorch.com.my/docs/2.2/custom-css-and-js#new-tool-or-asset`
2. Follow Steps
3. Refresh Larecipe Website

**Expected behavior**
The Asset should get loaded without any Error.

**Screenshots**
![image](https://user-images.githubusercontent.com/3144986/78776075-9381c780-7997-11ea-9fdd-4078b98fbfb1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 2.3.0

**Additional context**
None

**Comment by saleem-hadad** [comment]
The issue has been fixed in v^2.4, please also make sure to publish the new assets:

```
php artisan vendor:publish --tag=larecipe_assets --force
```
