### ISSUE TITLE
Two sibling Alerts fail visually

### ISSUE THREAD

**Issue by dschiller** [saleem-hadad/larecipe#214]
**Describe the bug**
If two Alerts follow after each other the second one will not be interpreted.

![image](https://user-images.githubusercontent.com/3144986/78796788-1403f080-79b7-11ea-866a-3f48fe72da4c.png)

**To Reproduce**
1. Use following Code:
```
> {primary} In Line **3** we import the **Webdriver** Module from the **Selenium** Module. This enables to have access
    to the Broweser.

> {primary} In Line **4** we import the **Keys** Module from the **Webdriver** Module. This enables us to use Key Constants
    like `Key.ENTER` which invokes a Enter Key Press
```
3. Open Larecipe Website

**Expected behavior**
![image](https://user-images.githubusercontent.com/3144986/78797351-dfdcff80-79b7-11ea-8a31-badf8d65c3b9.png)

**Note**: The to height distance between those two Alerts in this Screenshot comes from the added `<br/>` Code to make it possible to have two Alerts after each other. But if fixed the distance between two sibling Alerts for sure need to be smaller.

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 2.3.0

**Additional context**
None

**Comment by WillGoldstein** [comment]
Yes, I've seen this before. My work around has been inserting a break and then `<div></div>` and then the alert. So,

```
>{primary.fa-some-icon} Yay, an alert!

<div></div>
>{danger.fa-exclamation-triangle} Another lovely alert.
```

**Comment by dschiller** [comment]
Can you point me to the Point where the Parsing happens ? I can fix it then locally.

Thank's a lot!

**Comment by saleem-hadad** [comment]
for now, the workaround solution is by adding <br/> or what @WillGoldstein wrote.
You're welcome to submit a PR for a fix

**Comment by dschiller** [comment]
What is a PR ?

**Comment by WillGoldstein** [comment]
@dschiller don’t mean to sound rude mate but if you’re not sure what a pull request is, it’s unlikely you’ll Know how to fix this. I’d just stick with the work around and move on 🌲

**Comment by WillGoldstein** [comment]
@dschiller a pull request. Needs to pass unit tests too

**Comment by dschiller** [comment]
Thanks Will!
