### ISSUE TITLE
[text] is rendered improperly in a bullet point

### ISSUE THREAD

**Issue by tomposmiko** [saleem-hadad/larecipe#216]
**Describe the bug**
After a bullet point '[with any text or space]' is displayed to a checkbox like element, though it's not checkable. It is just a small square.
If it's not in a bullet point, the content displayed properly

**To Reproduce**
Add the following to an .md file and the difference is going to be clear.
```
* [aaa]
[aaa]
```
**Expected behavior**
The same behavior like outside a bullet point.

**Screenshots**
I can attach one if it's not reproducible.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Desktop
 - OS: any
 - Browser: FF, Chrome
 - Version: any

**Additional context**
-

**Comment by tomposmiko** [comment]
[text] also ruins a whole section of a page if it is contained by a table

**Comment by saleem-hadad** [comment]
you can use:
* aaa
* bbb
is that what are you looking for?
![Screen Shot 2020-09-09 at 12 09 20 AM](https://user-images.githubusercontent.com/12780866/92523033-b824e880-f230-11ea-8895-faa1af2b76d8.png)
