### ISSUE TITLE
Multiple alarm blocks are aggregated to one

### ISSUE THREAD

**Issue by tomposmiko** [saleem-hadad/larecipe#217]
**Describe the bug**
If there are more alarm blocks are after each other, they are displayed as one.

**To Reproduce**
This is displayed as a red warning block with the content of {info}.... too, they will not get separated to two unique blocks.
```
> {warning}
> aaa

> {info}
> bbb
```

**Expected behavior**
Something like similar to this:
```
> {warning}
> aaa

<br> 

> {info}
> bbb
```

**Screenshots**
I can provide a screenshot if needed.

**Desktop (please complete the following information):**
 - OS: desktop
 - Browser: FF, Chrome
 - Version: any

**Comment by saleem-hadad** [comment]
I think <br/> will solve it, please if you can propose a PR to solve it, please do.

**Comment by royduin** [comment]
This is still an issue. Please re-open.
