### ISSUE TITLE
Internal search not working in case of multiple versions.

### ISSUE THREAD

**Issue by classiebit** [saleem-hadad/larecipe#218]
**Error Description**
Internal searching only works in v1.0. When we create docs for v1.2 or v1.3, it does not work. When we click on the search icon, it shows - result not found.

Also, when we click on search icon, it shows a 500 internal server error in ajax call. 

This is the ajax URL - /docs/search-index/1.2
See the error traces in the screenshot attached.
[Error traces screenshot](https://uploads.disquscdn.com/images/8f2d953c031b118eb9da9b67bdbfb856e50942fe4e1c47e7f651872808570a42.png?w=800&h=685)

You can also have a look at the error live - 
[Online docs](https://eventmie-pro-docs.classiebit.com/docs/1.2/introduction)

**To Reproduce**
1. Create two versions of docs.
2. Switch to internal searching.
3. First, try in v1.0, the search will work.
4. Then, switch to another version v1.2, and click on the search icon. And you'll see the error.

**Screenshots**
[Error traces screenshot](https://uploads.disquscdn.com/images/8f2d953c031b118eb9da9b67bdbfb856e50942fe4e1c47e7f651872808570a42.png?w=800&h=685)

**Desktop (please complete the following information):**
 - Linux (Ubuntu 18.04)
 - Browser Chrome, safari
 - Version latest

**Comment by saleem-hadad** [comment]
please make sure you have a correct version structure.
after adding the version you need inside config/larecipe.php
run this command which will take care of the structure to make the search work.
```
php artisan larecipe:docs
```

See docs here: https://larecipe.binarytorch.com.my/docs/2.2/artisan-commands#docs-command 
and here: https://larecipe.binarytorch.com.my/docs/2.2/search#available-engines
