### ISSUE TITLE
Publishable assets to be all in public/vendor/binarytorch/larecipe

### ISSUE THREAD

**Issue by ijpatricio** [saleem-hadad/larecipe#22]
**Describe the bug**
Not sure it's a bug, but for sure an improvement to avoid collisions

**To Reproduce**
Some published assets are going to `public/fonts`

**Expected behavior**
Should have gone to `public/vendor/binarytorch/larecipe/assets/fonts`

**Additional context**
Paths interpreted relatively by mix/sass/webpack like in 

`resources/sass/vendor/font-awesome/css/font-awesome.css` line 9
```
  src: url('../fonts/fontawesome-webfont.eot?v=4.7.0');
```

will be output to the public folder webpack folder

but if we use "server relative" path like:

```
  src: url('/vendor/binarytorch/larecipe/assets/fonts/fontawesome-webfont.eot?v=4.7.0');
```

will "trust" it's there, so after the publishing `php artisan larecipe:install` all works nice!

I've already done that in my fork, check [here](https://github.com/ijpatricio/larecipe/tree/feat/public-assets)

If you like the idea, just tell me and I send PR

after picture, note the font aweosome icon with `<i class="fa fa-icon fa-align-left"></i>`:

also inspector and proper font decoding manually checked

![image](https://user-images.githubusercontent.com/26031459/45486181-1c039c00-b752-11e8-8f1a-c2d55cc31034.png)

**Comment by saleem-hadad** [comment]
Hi @ijpatricio 
Thank you for addressing this issue. You're right actually, all the assets should go to the same vendor.
Please proceed with your PR 👌
