### ISSUE TITLE
Error when creating asset

### ISSUE THREAD

**Issue by mokchend** [saleem-hadad/larecipe#220]
**Describe the bug**
When trying to create a larecipe asset, it failed with 

**To Reproduce**
1. php artisan larecipe:asset test/demo
2. yes
3. See error
 TypeError

  Argument 1 passed to Symfony\Component\Process\Process::__construct() must be of the type array, string given, called in /Users/cmok/code/demoproject/vendor/binarytorch/larecipe/src/Traits/RunProcess.php on line 18

  at vendor/symfony/process/Process.php:140
    136|      * @param int|float|null $timeout The timeout in seconds or null to disable
    137|      *
    138|      * @throws LogicException When proc_open is not installed
    139|      */
  > 140|     public function __construct(array $command, string $cwd = null, array $env = null, $input = null, ?float $timeout = 60)

**Expected behavior**
The asset creation must be successfull

**Screenshots**

**Desktop (please complete the following information):**
 - OS: mac
 - Browser: N/A
 - Version : 
       "laravel/framework": "^7.0",
        "axelrindle/larecipe-emojify": "^1.0",
        "binarytorch/larecipe": "^2.3",

**Comment by Butochnikov** [comment]
Same error

**Comment by saleem-hadad** [comment]
fixed now in v2.4.3. please upgrade.
