### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by productiveparks** [saleem-hadad/larecipe#222]
**Describe the bug**
I run >composer require binarytorch/larecipe and all is fine
Then when I run >php artisan larecipe:install I get the following error:

Publishing assets and congigurations.. 🍪
Copied Directory [\vendor\binarytorch\larecipe\publishable\assets] To [\public\vendor\binarytorch\larecipe\assets]
Copied File [\vendor\binarytorch\larecipe\publishable\config\larecipe.php] To [\config\larecipe.php]
Copied Directory [\vendor\binarytorch\larecipe\resources\views\partials] To [\resources\views\vendor\larecipe\partials]
Publishing complete.
Setup initial documentations structure under .. 🍪

   ErrorException

  implode(): Invalid arguments passed
  at C:\pmms\vendor\binarytorch\larecipe\src\Commands\GenerateDocumentationCommand.php:52
    48|     public function handle()
    49|     {
    50|         $publishedVersions = config('larecipe.versions.published');
    51|
  > 52|         $this->info('Reading all docs versions, found: '.implode(',', $publishedVersions));
    53|         foreach ($publishedVersions as $version) {
    54|             $versionDirectory = config('larecipe.docs.path').'/'.$version;
    55|
    56|             $this->line('');

  1   C:\pmms\vendor\binarytorch\larecipe\src\Commands\GenerateDocumentationCommand.php:52
      implode(",")

  2   C:\pmms\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:33
      BinaryTorch\LaRecipe\Commands\GenerateDocumentationCommand::handle()

**Comment by stephenstack** [comment]
Getting this also. Any fix or workaround?

**Comment by stephenstack** [comment]
For me, i had to run a php artisan config:cache

When debugging, i found that the GenerateDocumentationCommand was returning null for the 
$publishedVersions = config('larecipe.versions.published');

When testing with other config files, arrays were returned. Working for me now, so might need to be tested further.

**Comment by productiveparks** [comment]
Thank you, Stephenstack. That did it. I had seen the same thing, that the published versions was returning null. Clearing and rebuilding the config cache fixed it for me too.
