### ISSUE TITLE
Escape Double Curly Brackets {{}}

### ISSUE THREAD

**Issue by MakamuEvans** [saleem-hadad/larecipe#223]
**Describe the bug**
Am trying to escape the curly square brackets in one of my pages but it brings up a parse error

**To Reproduce**
Write on any Larecipe pages a double curlly MD code.
I've even added the escape syntax.

something with curlky brackets like {{ this }} and { that }
 

**Expected behavior**
Should output "**something with curlky brackets like {{ this }} and { that }**"

**Screenshots**

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser CHrome
 - Version 81
<img width="1271" alt="Screenshot 2020-05-11 at 16 31 19" src="https://user-images.githubusercontent.com/22904324/81567468-04583d00-93a5-11ea-8c5b-3efb4c37b0b1.png">

**Comment by saleem-hadad** [comment]
please add @ before {{}} as a workaround to make it work
