### ISSUE TITLE
Code throws ParseError

### ISSUE THREAD

**Issue by dschiller** [saleem-hadad/larecipe#224]
This Code throws a Parse Error:

```
'''python
@step('Checkbox {element:QuotedString} Label is {label:QuotedString}')
def stepImpl(step, element, label):
    global driver
    returnedElement = driver.find_element(By.XPATH, "//*[@for='%s']//label[text()]"%element)
    returnedLabel = returnedElement.text
    assert returnedLabel == label, 'Expected Label `%s` is not equal to `%s`.'%(label, returnedLabel)
'''
```

It's exactly this Line:
```
returnedElement = driver.find_element(By.XPATH, "//*[@for='%s']//label[text()]"%element)
```

![image](https://user-images.githubusercontent.com/3144986/82271326-c0060780-9977-11ea-92df-43e04129d95c.png)

Workaround is:
```
returnedElement = driver.find_element(By.XPATH, "//*[@@for='%s']//label[text()]"%element)
```
![image](https://user-images.githubusercontent.com/3144986/82271568-681bd080-9978-11ea-91bb-add426f24bde.png)

**Comment by saleem-hadad** [comment]
fixed in v2.4.3
![Screen Shot 2020-09-08 at 11 57 18 PM](https://user-images.githubusercontent.com/12780866/92521909-118c1800-f22f-11ea-84b8-cf9f11452ba4.png)
