### ISSUE TITLE
Admin Backend Panel to Create Documentation?

### ISSUE THREAD

**Issue by lucabecchetti** [saleem-hadad/larecipe#226]
is there a backend with WYSiWYG editor to create markdown files?

**Comment by WillGoldstein** [comment]
No

**Comment by saleem-hadad** [comment]
Not yet, will be in v3

**Comment by lucabecchetti** [comment]
when do you plan to release?

**Comment by saleem-hadad** [comment]
Not sure, at the moment my schedule is almost full so working slowly slowly.
