### ISSUE TITLE
Checkbox regex replaces irrelevant stuff

### ISSUE THREAD

**Issue by LockonZero** [saleem-hadad/larecipe#232]
**Describe the bug**
Text inside lists is being replaced with HTML checkboxes

**To Reproduce**
1. Inside a Markdown file create a Markdown list (number of elements does not matter)
2. Inside the list add content enclosed in square braces ([this is a test])
3. Render the result on the frontend
4. Text has been replaced with checkbox

**Expected behavior**
Only squares braces which are empty or only contain 'x' should be replaced with an HTML checkbox (maybe only when they are in the beginning of a list item)

**Screenshots**
If needed I can provide screenshots, but the description above should be enough.

**Desktop (please complete the following information):**
 - OS: Any OS
 - Browser Any Browser
 - Version All versions

**Additional context**
I think that the regex `/\[.+\]/` on line 163, in file resources/js/Larecipe.js is too broad for the case that it is used for. I could try submitting a PR if there is no time to fix this

Thanks a lot for all the awesome work that you have done in this package :)

**Comment by saleem-hadad** [comment]
fixed in v2.4.3
