### ISSUE TITLE
Static site generator

### ISSUE THREAD

**Issue by ijpatricio** [saleem-hadad/larecipe#24]
**Is your feature request related to a problem? Please describe.**
It's not a problem, it's a feature
This is referenced in a closed issue already, and was added to the `Future development` issue. https://github.com/saleem-hadad/larecipe/issues/6#issue-356650254

**Describe the solution you'd like**
Generating static assets files.

**Additional context**
I already have in my fork local copy a cool way to do this, just hope we could align some thoughts??

1. Generating all versions, right??
2. Parsing the needed files, by the index.md, yes?
```
<ul>\n
<li>\n
<h2>Get Started</h2>\n
<ul>\n
<li><a href="/docs/1.0/overview">Overview</a></li>\n
</ul>\n
</li>\n
<li>\n
<h2>Another secion</h2>\n
<ul>\n
<li><a href="/docs/1.0/awesome-page">Awesome Page</a></li>\n
</ul>\n
</li>\n
</ul>
```
3. base path - getting from config?? -> like for `/` or `/docs/`

it's cool that you are already using `larecipe_assets()` for url generation, we can change helper and make something diffferent if generating static assets 😉 

4. Cool to keep friendly-urls, right?
example, for above index in (2) would generate files as following:
```
docs/index.html
docs/1.0/overview/index.html
docs/1.0/awesome-page/index.html
```

Does it make sense?

5. the publishables by `larecipe:install`, would also be copied as they are, right??
or else they would have to be republished...

6. the static assets could be forbidden to published for same base as the dynamic?
because after publishing, if they are in same `uri`... then the webserver would serve the files, instead of going through laravel's route

7. What if the `larecipe:static` command would just publish to a configuration path, defaults to `static` and it would go to `public/static/**/**`

Problem is they would not work immediately... the contents of `static` would have to be copied to a root folder (or the specified base path)

Is this ok to live with??

**Comment by ijpatricio** [comment]
I mean: the above I stated, I would be ready to develop and PR

**Comment by saleem-hadad** [comment]
Thank you @ijpatricio  for the details you provided, and sorry for being late I was busy a bit.
However, in my opinion:
1. Yes
2. Yes
3. I think `/` is better since the website will be hosted statically 
4. hmm confused me a bit, have to thought about Vue router? 
5. yes
6. not sure
7. cool

Now from my side, I was discussing this feature with my teammate and he suggested to build CLI or to build something similar to Vuepress functionalities where you don't need any prior knowledge in Laravel to use this package (he is a c# fan 🤣). However, till now I don't have a clear vision about this feature but what the things you  suggested until now are awesome 😍

**Comment by ijpatricio** [comment]
Hmmm sure 👍 

I like Vuepress very much, and what made me look into yours, is that is Laravel powered...
Thing is, for me, I can't contribute to Node apps as I can with Laravel...

So, IMO, don't change what makes this package so awesome 😃 

Thank you for your words ❤️ 

Please clarify, you will work on this, or can I start something?

Also, nice to see you tagged Snippet Import https://github.com/saleem-hadad/larecipe/issues/25
As you still didn't answer, I was not sure you would like that.

Which one would you prefer I develop, `static_assets` or `snippets_import`?

**Comment by saleem-hadad** [comment]
Thank you very much dude 😍
I saw the #25  but I didn't actually get the full picture of it.
However, I prefer to work on this feature (static_assets) and you on that one 👻 (snippets_import)
And we keep Laravel powered 😆👌

**Comment by saleem-hadad** [comment]
and sorry for being late I was working on implementing search and forum features
now one of my teammates will join us to work on built-in search support in addition to Algolia for those who have used the package privately.

**Comment by saleem-hadad** [comment]
will be added to the pro version as stated [here](https://github.com/saleem-hadad/larecipe/issues/6#issuecomment-568933034)
