### ISSUE TITLE
url generation incorrectly

### ISSUE THREAD

**Issue by Busuzima** [saleem-hadad/larecipe#243]
Hi,

i've installed larecipe on my laravel project in a local xampp environment, so i have a structure like
baseurl: localhost/projectname/public
docs route: /docs

in my index.md:
i have something like
`- ## Dashboard
    - [Overview](/{{route}}/{{version}}/dashboard/overview)`

if i go on the generated link this point to:
localhost/docs/1.0/dashboard/overview
causing a 404 error.

Can someone help me generating a correct link?

Thanks in advance

**Comment by saleem-hadad** [comment]
can you show your resources/docs directory?

**Comment by Busuzima** [comment]
sure,

**Comment by Busuzima** [comment]
btw forgot to mention that for this project i have laravel framework 5.5.5 and larecipe 2.2.3
