### ISSUE TITLE
Internal search 500 error

### ISSUE THREAD

**Issue by Neikas** [saleem-hadad/larecipe#248]
**Describe the bug**
Internal search is not working then using  "( text )" in index.md

**To Reproduce**
1. Go to 'index.md'
2. Change    " - [Testing ( Test1) ](/{{route}}/{{version}}/test/testtt)"
3. Press on search in web
4. See error 500 search doesn't work 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Win 10]
 - Browser [e.g. chrome]

**Additional context**

**Comment by McCaulay** [comment]
@Neikas Just came across the same problem, i've created a PR for a fix.

#251

**Comment by saleem-hadad** [comment]
fixed in v2.5.0
