### ISSUE TITLE
Code snippet import

### ISSUE THREAD

**Issue by ijpatricio** [saleem-hadad/larecipe#25]
**Is your feature request related to a problem? Please describe.**
I already mentioned in `future development` https://github.com/saleem-hadad/larecipe/issues/6#issuecomment-420966753
but i'm not sure if you are seeing it...

**Describe the solution you'd like**

**Describe alternatives you've considered**

It's very useful for technical docs, and usage without having to change the source code.

Something like... -> single quote used to be seen as code block in this comment

```
'```snippet-php

filePath: app/MyClass.php 

firstLineQuery: public function myMethod

paddingTop: 4

lastLineQuery: return $something;

paddingBottom: 3

fileNumbers: true

highlightLinesQuery: some text

highlightLinesQuery: another text

'```
```

Description for inputs:

- filePath: `relative to base path`, using later: `base_path('app/MyClass.php')`
- first line query: `public function myMethod`
   (will find first line in file, with occurence of `public function myMethod`, and mark its line number)
   - If an integer, just use that integer as the line
- last line query: `return $something;`
   (will find first line in file, with occurence of `return $something;`, and mark its line number)
   - If an integer, just use that integer as the line
- lastLine > firstLine or throwException
- fileNumbers: `boolean`
   use the line numbers from file
- paddingTop/paddingBottom: `signedInteger`
   (padding to change first line and last linefor snippet) - useful for not having to place markers in source files
- highlightLinesQuery: [`some text`,`another text`]
   will highlight lines containing `some text` and `another text` 

**Additional context**

Similar to something I've done [here](https://github.com/ijpatricio/nova-larastan-tool)

![codemirrorusage](https://github.com/ijpatricio/nova-larastan-tool/raw/master/docs/NovaLarastanTool.png)

I already checked prism.js, all this is possible easily, check this plugin https://prismjs.com/plugins/line-numbers/

What do you think?

I will do it for me, but checking if we have alignment, maybe for another PR? 😄

**Comment by ijpatricio** [comment]
Nice that it wasn't closed. I believe very soon i'll be able to contribute this feature.

**Comment by saleem-hadad** [comment]
Of course not, I understand we have other things to focus on as well, totally understand :D 
Awesome that you get back working on it 😍❤️

**Comment by saleem-hadad** [comment]
will be added to the pro version as stated [here](https://github.com/saleem-hadad/larecipe/issues/6#issuecomment-568933034)
