### ISSUE TITLE
Possibility to disable docs routes 

### ISSUE THREAD

**Issue by johnylemon** [saleem-hadad/larecipe#250]
Will be good if package config will allow developer to disable docs routes sometimes.

Actually I want to publish docs because it is not ready to be public yet, but is good enough for developers

**Comment by WillGoldstein** [comment]
Definitely possible. Just read the docs! https://larecipe.binarytorch.com.my/docs/2.2/authorization

**Comment by johnylemon** [comment]
I did not see this simple example ;-)
Thank you +1: :-)
