### ISSUE TITLE
Switch prism.js to highlight.js

### ISSUE THREAD

**Issue by Zanzavar** [saleem-hadad/larecipe#267]
Is it possible to change the default code highlighting language from prism.js to e.g. highlight.js? I am using a custom language described in highlight.js in my app and would be great to be able to include it as is in the documentation.

Looked around the larecipe docs could not find something related. Thanks for the help!

**Comment by saleem-hadad** [comment]
I think that's possible if you create a custom asset for your documentation, please let me know if this can help:
https://larecipe.binarytorch.com.my/docs/2.2/custom-css-and-js

to get more insights on how to build your extension please see some examples here:
https://github.com/larecipe
