### ISSUE TITLE
Backend ideas?

### ISSUE THREAD

**Issue by jrmypttrsn** [saleem-hadad/larecipe#274]
I have users who want to be able to create and edit the markdown files. These users are non-developers and thus don't have access to the repo. I'd like to have some kind of admin access for this and I'm not sure which way to go about it: using something like Spatie's [Sheets](https://github.com/spatie/sheets) or maybe [Blogged](https://github.com/saleem-hadad/blogged)?

Any thoughts would be appreciated.

**Comment by saleem-hadad** [comment]
Hello, 
Yes I have a plan to support this after v3

**Comment by saleem-hadad** [comment]
Yes December 25th
