### ISSUE TITLE
Blade syntax break resolution

### ISSUE THREAD

**Issue by stygiansabyss** [saleem-hadad/larecipe#28]
**Describe the bug**
When using a snippet that contains blade, the documentation page will no longer load in a browser

**To Reproduce**
```blade
    <a href="{{ route('auth.social.login', ['google']) }}">Log in with Google</a>
    <a href="{{ route('auth.social.login', ['github']) }}">Log in with Github</a>
```

Place this snippet anywhere in a larecipe markdown file.

**Expected behavior**
It should show blade syntax as just text.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Additional Information**
I even tried using `&#123;` and `&#125;` for the braces but it just displays them as is instead of converting to curly brackets.

**Comment by saleem-hadad** [comment]
Thank you @stygiansabyss  for addressing this issue, we'll work on solving it.
Please suggests your solution if you have one.

**Comment by saleem-hadad** [comment]
@stygiansabyss This issue has been solved by @phannaly and it will be available in the next version. See (#35)
