### ISSUE TITLE
Markdown list not working properly 

### ISSUE THREAD

**Issue by Zubair-Iftikhar** [saleem-hadad/larecipe#286]
**Describe the bug**
List of Requirements showing right side of the page.

**Expected behavior**
List of requirements will be shown after paragraph.
Expected output will like this
![expected](https://user-images.githubusercontent.com/11349938/137920547-f4b3574e-ec31-45e7-b453-f9c549259780.PNG)

**Screenshots**
in larecipe it's look like
![Code](https://user-images.githubusercontent.com/11349938/137919925-ebb81888-da0b-4257-be33-6491c4411b7b.PNG)

![Out Put](https://user-images.githubusercontent.com/11349938/137919965-ff90ce83-2b2e-4e6c-919a-2e0b477559ea.PNG)

**Desktop:**
 - OS: Windows 10
 - Browser Chrome
 - Version Version 94.0.4606.81 (Official Build) (64-bit)

**Additional context**

**Comment by saleem-hadad** [comment]
This is because that LaRecipe will assume the first list you have is the table of content. This is fixed in v3 but will take time to be rolled out. 
https://larecipe.saleem.dev/docs/2.2/markdown-support#toc
