### ISSUE TITLE
Laravel 9 support?

### ISSUE THREAD

**Issue by Stunext** [saleem-hadad/larecipe#292]
Composer Problem:

    - Root composer.json requires binarytorch/larecipe ^2.4 -> satisfiable by binarytorch/larecipe[v2.4.0, ..., 2.x-dev].
    - binarytorch/larecipe[v2.4.0, ..., 2.x-dev] require illuminate/support ^5.4|^6.0|^7.0|^8.0 -> found illuminate/support[v5.4.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

**Comment by Stunext** [comment]
Solve in #294. Waiting for the changes to merge

**Comment by abishekrsrikaanth** [comment]
Any chance of merging #294?

**Comment by colinmackinlay** [comment]
Yes please #294

**Comment by Stunext** [comment]
Temporarily I use the Shift's fork

In composer.json:
```
{
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/laravel-shift/larecipe.git"
        }
    ]
}
```
Then update your dependency constraint to reference this branch:
```
{
    "require": {
        "binarytorch/larecipe": "dev-l9-compatibility",
    }
}
```
Finally, run: composer update

**Comment by flolanger** [comment]
Though it would be nice if #294 gets merged soon. I'm also waiting for this. :)

**Comment by saleem-hadad** [comment]
Hello everyone,
sorry for the late response since I was on vacation, will try to merge it by this weekend.

**Comment by saleem-hadad** [comment]
Live in v2.5 🎉
