### ISSUE TITLE
Multiple Document

### ISSUE THREAD

**Issue by yazan-alnugnugh** [saleem-hadad/larecipe#293]
I was wondering if the package can be used for more than one document

**Comment by ammardev** [comment]
Take a look at the versioning feature in the docs:
https://larecipe.binarytorch.com.my/docs/2.2/configurations#versions

**Comment by yazan-alnugnugh** [comment]
I mean if I have 2 docs, for each doc has versions 
I don't mean for version but for docs

**Comment by ammardev** [comment]
As I remember,

The documentation has many versions, a version may have many pages. You can't create many documents but you can create many versions (A version for each doc).

I know that this is not perfect but it may be useful in some cases:

```v1.4.3-api```

and

```v2.2.7-portal```

**Comment by saleem-hadad** [comment]
Hi @yazan-alnugnugh 
Unfortunately, there's no plan to support multiple projects docs.

**Comment by WillGoldstein** [comment]
@yazan-alnugnugh I just used the versioning functionality to have multiple "projects" within the same SaaS. Like aircraft owners, MROs, etc was the name of the version of the docs

**Comment by yazan-alnugnugh** [comment]
@WillGoldstein 
This package is really great but unfortunately it doesn't work with multiple documents I had to make something custom

**Comment by yazan-alnugnugh** [comment]
@ammardev @saleem-hadad 
I would like to thank you for this great work and thank you for helping me
