### ISSUE TITLE
Prism Autoloader

### ISSUE THREAD

**Issue by tankerkiller125** [saleem-hadad/larecipe#30]
---
name: Feature request
about: Suggest an idea for this project

---

**Is your feature request related to a problem? Please describe.**

Prism does not by default support many languages in this package, this can cause issues for some use cases, and providing all languages the way the current prism setup is designed would result in a very large unusable file.

**Describe the solution you'd like**

One of the many plugins available to Prism is the Autoloader which allows for the prism script to automatically grab the appropriate language definitions from an url and only the languages used on the page. I think that it would be greatly beneficial to use this feature as it would allow this Laravel package to provide syntax highlighting for all languages and it would also keep the load time lower overall, especially on HTTPS connections supporting HTTP2. Unfortunately, I can't seem to find a CDN that host the files so it may have to be part of the actual published files.

**Describe alternatives you've considered**

HighlightJS/None

**Additional context**

I think support for all the languages would be great for many developers.

**Comment by saleem-hadad** [comment]
Thank you @tankerkiller125 for your thought. You're right about that but no planning for this feature at least in this year. However, feel free to suggest and contribute with your solution if you prefer working on this.
Also, I'll add your request to the [development feature](https://github.com/saleem-hadad/larecipe/issues/6) board so others might implement it.

Thank you very much 🍀
