### ISSUE TITLE
How do I use custom vue component inside markdown?

### ISSUE THREAD

**Issue by paramwork** [saleem-hadad/larecipe#303]
I have created a vue component in `/resources/js/VueComponent.vue`.

I want to use this component inside markdown? How do I do it?

I try using publishing the custom theme and try to add vue component but it does not load because it overrides id="app" 

`LaRecipe::script('app-vue', asset('js/app-vue.js'));`

Please help me integrate this. Thank you in advance.

**Comment by saleem-hadad** [comment]
you can do that by custom plugin where you can inject any vue component you like
https://larecipe.saleem.dev/docs/2.2/custom-css-and-js
