### ISSUE TITLE
cannot make deployment on heroku 

### ISSUE THREAD

**Issue by 2003100127** [saleem-hadad/larecipe#305]
Hi Larecipe Team,

I cannot currently deploy a laravel (larecipe built-in) project in herokuapp. If made upon blade files, herokuapp can recognize the project well. But I cannot visit the larecipe doc website. In my local PC, the larecipe docs run well. Could you please have a simple test on deploy a demo laravel (larecipe built-in) project in herokuapp or any solutions for this? I do not know if there are any tips to enable this. I really appreciate it.

Best,
2003100127

**Comment by saleem-hadad** [comment]
Hey, 
I'm not familiar Heroku sorry.
