### ISSUE TITLE
Add custom html tags to <head>

### ISSUE THREAD

**Issue by sentiasa** [saleem-hadad/larecipe#308]
It'd be nice if I can pass some tags from larecipe config to <head>, so that I can add some meta tags.

My use-case is that, I have a sandbox website, and I don't want the larecipe docs to be crawled by Google. Even though, I have my robots.txt file properly, it seems like I need to add robots meta tag in the html and unfortunately there is no way to achieve it.

```
head_meta_tags => [
    env('IS_SANDBOX') ? "<meta name="robots" content="noindex">" : ''
]
```

I can create this and create a PR - what do you think?

**Comment by saleem-hadad** [comment]
I think you can do that by default laravel supports that. Just override the file here https://github.com/saleem-hadad/larecipe/blob/master/resources/views/default.blade.php and add the headers you like.
