### ISSUE TITLE
There is no fixation menu on the left in the Microsoft Edge browser

### ISSUE THREAD

**Issue by scriptixru** [saleem-hadad/larecipe#31]
When you click the lock menu at the top left, there is no commit. When you move to a new item, the menu disappears. Under the Microsoft Edge browser.

**Comment by saleem-hadad** [comment]
Thanks @scriptixru for addressing this issue, but could you please provide a picture or more details about the bug?

**Comment by scriptixru** [comment]
Microsoft Edge 42.17134.1.0
Microsoft EdgeHTML 17.17134
Bug References:
[http://scriptix.dx.am/images/bug_1.jpg](http://scriptix.dx.am/images/bug_1.jpg)
[http://scriptix.dx.am/images/bug_2.jpg](http://scriptix.dx.am/images/bug_2.jpg)
[http://scriptix.dx.am/images/bug_3.jpg](http://scriptix.dx.am/images/bug_3.jpg)
[http://scriptix.dx.am/images/bug_4.jpg](http://scriptix.dx.am/images/bug_4.jpg)

**Comment by saleem-hadad** [comment]
Fixed in the latest versions
