### ISSUE TITLE
Too much css gets sent to the page (build)

### ISSUE THREAD

**Issue by jannismilz** [saleem-hadad/larecipe#317]
**Describe the bug**
When I use the LaRecipe package and render my site it generally it works. But sometimes the CSS doesn't get loaded on first try because of `ERR_CONTENT_LENGTH_MISMATCH`.
After some digging into it I saw that you @saleem-hadad just export all data from fontawesome, tailwind etc. and ship it. I know that I could increase the max length but that's not the case, it's just too much and especially too much unused CSS that gets shipped. 

**To Reproduce**
- Just switch from page to page a few times until you once only see the HTML rendered without CSS.

**Expected behavior**
Render the page with its HTML, CSS and JS.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome/Safari
 - Version: Chrome (109.0.5414.87), Safari (16.1)

**Comment by saleem-hadad** [comment]
this is planned to be fixed in v3
