### ISSUE TITLE
Any news about Laravel 10?

### ISSUE THREAD

**Issue by ManukMinasyan** [saleem-hadad/larecipe#318]
When do you plan to update this package for Laravel 10?

**Comment by ebalo55** [comment]
I see that in 2022 there was a Laravel Shift commit on the release date of Laravel 9 so probably the same will happen this year, if the owner have enabled the auto-publishing feature an update will be release automatically, if not the owner must merge the pull and create a new release

**Comment by saleem-hadad** [comment]
yes soon.

**Comment by saleem-hadad** [comment]
v2.6.0 now supports Laravel 10
