### ISSUE TITLE
Make dark mode as toggle option

### ISSUE THREAD

**Issue by aeq-dev** [saleem-hadad/larecipe#319]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
-

**Describe alternatives you've considered**
-

**Additional context**
If we can set a toggle button to switch themes dark/light.
Also if it's possible to save the current theme (dark or light) in localStorage of browser (same as filament does :) )
Thanks

**Comment by saleem-hadad** [comment]
yes, this will be available in v3.
