### ISSUE TITLE
404 after install

### ISSUE THREAD

**Issue by daniellord32** [saleem-hadad/larecipe#327]
**Describe the bug**
I get the following error after following the install
![image](https://github.com/saleem-hadad/larecipe/assets/25160505/9f27ca58-149d-437b-b821-9fac3e8372fd)

**Steps to try and fix **
I've ran optimize
I've ran composer dump -autoload
I've added relevant line to providers section in app.php
I've ran the following command: php artisan vendor:publish --tag=larecipe_assets --force
I've tried the install command again

**Desktop (please complete the following information):**
 - OS: Linux ubuntu
 - Browser chrome
 - Version 2.6
 - laravel version: 8
 - php version: 8

**Comment by saleem-hadad** [comment]
most probably it's a server issue. please confirm if this is still relevant.
