### ISSUE TITLE
Multiple Docs Site

### ISSUE THREAD

**Issue by luchtech** [saleem-hadad/larecipe#330]
So I came upon your package and it really seems cool! Just wondering if your package can create multiple documentation for my packages.

For example, `luchavez/starter-kit` will be available on `/docs/starter-kit`, `luchavez/boilerplate-generator` will be available on `/docs/boilerplate-generator`, and so on.

**Comment by luchtech** [comment]
Something like a multi-tenant docs I guess? But the tenants this time are my packages. 😅

**Comment by dcblogdev** [comment]
unfortunately this is not supported see https://github.com/saleem-hadad/larecipe/issues/293#issuecomment-1079464107

would be really useful to have that.
