### ISSUE TITLE
Publish lareceipe docs site

### ISSUE THREAD

**Issue by ssx** [saleem-hadad/larecipe#333]
Could you publish the larecipe docs so we can see how pages are built? This is asked in a few issues.

**Comment by ssx** [comment]
tagging @saleem-hadad 🙂

**Comment by saleem-hadad** [comment]
yes sure, please find the details here
https://github.com/larecipe

**Comment by saleem-hadad** [comment]
https://github.com/larecipe/larecipe-docs

**Comment by ssx** [comment]
thanks @saleem-hadad 🙂
