### ISSUE TITLE
[Question] Adding more Prism syntaxes

### ISSUE THREAD

**Issue by OwenMelbz** [saleem-hadad/larecipe#34]
Adding extra Prism syntax highlighting?

Hi - I've seen that currently you only support a handful of syntax highlighting e.g. php, html, js, etc.

However, we're looking to have some of the more commonly used Laravel syntaxes e.g

dotenv, sql etc

How can we go about adding extra syntaxes?

Thanks

**Comment by tankerkiller125** [comment]
So far it seems that the best way is by downloading your own prism.js file and replacing the one that the package comes with. I'm currently looking into doing a Prism Autoload setup but it unfortunately can't use a CDN like I want it to.

**Comment by saleem-hadad** [comment]
Thank you guys for making this package perfect 👌
The PR merged now, next release will be tonight 🎊
