### ISSUE TITLE
Question : How to setup RTL ?

### ISSUE THREAD

**Issue by aeq-dev** [saleem-hadad/larecipe#347]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by saleem-hadad** [comment]
you can use this small extension
```
composer require binarytorch/larecipe-rtl
```

**Comment by aeq-dev** [comment]
Thanks for reply,
But I want to add rtl support, I mean users can browse both ltr or rtl :)
This rtl package removes ltr as I see

**Comment by aeq-dev** [comment]
Hi @saleem-hadad 
Is v3 available ? can't setup rtl installing latest version ! Thanks
