### ISSUE TITLE
Custom url inside index.md

### ISSUE THREAD

**Issue by rayout** [saleem-hadad/larecipe#37]
**Is your feature request related to a problem? Please describe.**
If I changed docs.route from docs to documentation, then I need to change all paths inside index.md

**Describe the solution you'd like**
I would like to have a keyword like {{version}} but for route.

**Comment by saleem-hadad** [comment]
Thank you @rayout for this nice idea 😄
Now it's supported and you can use `{{route}}` placeholder to make it dynamic, just pull the new version `v1.2.3` of LaRecipe. See here ([#fd21ce2](https://github.com/saleem-hadad/larecipe/commit/fd21ce228a5934976c8f8d20230c60097891746c)).
