### ISSUE TITLE
sidebar

### ISSUE THREAD

**Issue by vortechron** [saleem-hadad/larecipe#4]
sidebar toggle should be cache. its very pain to re-toggle back when refreshing page or visit another section.

**Comment by saleem-hadad** [comment]
Thank you @vortechron for your feedback. 
I thought about it but I think the reason for making the sidebar hidden is to make the user focus more on the content without distractions. However, it's worth to mention we should cache the user preference if we assume the user navigate a lot. We will consider this feature in the upcoming version.

Thank you.

**Comment by saleem-hadad** [comment]
Hope the keyboard shortcut `/` helps you for now 😇.

**Comment by vortechron** [comment]
@saleem-hadad your welcome 👍 ,  btw i really love the design and overall of this package.. im definitely going to use this package alot 💯 thank you

**Comment by saleem-hadad** [comment]
My pleasure 😍

**Comment by vortechron** [comment]
@saleem-hadad yeah, im currently using ```/``` shortcut. but caching toggle is must have tho haha

**Comment by steveheinsch** [comment]
I do agree with the above. It was the first thing I noticed as well. It should remember your open/closed preference. This does look really nice, so good job!

**Comment by saleem-hadad** [comment]
Thank you guys @vortechron  @steveheinsch   💘 

It out there now: [v1.0.1](https://github.com/saleem-hadad/larecipe/releases/tag/v1.0.1) 🎉
