### ISSUE TITLE
Issue with second and even other non-first level lists.

### ISSUE THREAD

**Issue by Windstep** [saleem-hadad/larecipe#42]
**Describe the bug**
List inside of list will cause a problem of rendering because of "first-of-type" directive in css. All Lists of second level will be thrown to the right side of the application.

**To Reproduce**
1) Install
2) Add two unordered lists one inside each other.
3) Open the page

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 18.04
 - Browser [e.g. chrome, safari] Chrome 69 (latest)
 - Version [e.g. 22] (latest)

**Comment by Windstep** [comment]
Fix is very simple. Change the definition of the rule 
`.documentation .article ul:first-of-type` to `.documentation .article > ul:first-of-type`

**Comment by saleem-hadad** [comment]
Thank you @Windstep 👍
