### ISSUE TITLE
Latest version causing issue in HasBladeParser.php

### ISSUE THREAD

**Issue by tnylea** [saleem-hadad/larecipe#44]
**Describe the bug**
On PHP 7.1 error in HasBladeParser.php

**To Reproduce**
1. Install a new version using PHP 7.1
2. Visit the introduction page or the docs page

**Expected behavior**
Expect to see the docs

**Screenshots**
![screen shot 2018-09-25 at 6 53 54 am](https://user-images.githubusercontent.com/601261/46019050-1716e480-c090-11e8-8d08-a969198ce5f4.png)

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra
 - Chrome
 - Version 68

**Additional context**
My solution was to downgrade to 1.2.3 because 1.2.4 was giving me this error.

Just wanted to post this incase someone else runs into it.

Thanks.

**Comment by phannaly** [comment]
@tnylea this is my feature, I will look at this soon. Thank for addressing the issue.

**Comment by phannaly** [comment]
Hi @tnylea I have tested it with a fresh install on My MacOS Sierra, PHP7.1 and work normally. Can you try a fresh install again?

**Comment by tnylea** [comment]
@phannaly Thanks for addressing this.

It turns out in my overview.md, I put some links to other pages of the documentation and when I use the:

```
{{version}}
```

Variable I get an error.

Try this out, put this inside of your `overview.md`

```
[Link](/docs/{{version}}/features)
```

And it will throw an error instead of creating the link for the specific version.

Thanks again 👍 Let me know if I can do anything to help on my end.

**Comment by phannaly** [comment]
@tnylea `{{version}}` doesn't work in other markdown files beside index.md. If you want this, you need to do this.
Inside `DocumentationController`
```php
public function show($version, $page = null)
    {
        $data = ["version" => "1.0"]; // any version as you want
        $documentation = $this->documentationRepository->get($version, $page, $data);
```
And inside `overview.md`

```markdown
[Link](/docs/{{$version}}/features)
```

**Comment by saleem-hadad** [comment]
Thank you @tnylea for addressing this issue.
I know what is causing this
In the feature added by @phannaly the blade renders the content before replacing the versions placeholders in the docs.
I've fixed the issue now by changing the order only 😂 [see](https://github.com/saleem-hadad/larecipe/commit/43e1195ac985519747dcb871daa39f40bc749f0a)

**Comment by tnylea** [comment]
Thanks guys 👍
