### ISSUE TITLE
Since latest update - Blade directives now break the page

### ISSUE THREAD

**Issue by OwenMelbz** [saleem-hadad/larecipe#46]
**Describe the bug**
Since updating to `v1.2.5` our templates which use example blade directives in them now break with the error...

```
Undefined variable: __env
```

**To Reproduce**
Create a `blade.md` doc with content such as

```html

# 🔪 Blade

---
```html
<!-- Stored in resources/views/layouts/app.blade.php -->

<html>
    <head>
        <title>App Name - @yield('title')</title>
    </head>
    <body>
        @section('sidebar')
            This is the master sidebar.
        @show

        <div class="container">
            @yield('content')
        </div>
    </body>
</html>
```

Visit page and it errors

**Expected behavior**
Page doesn't error :D

**Screenshots**
<img width="1010" alt="whoops__there_was_an_error_" src="https://user-images.githubusercontent.com/1094740/46297933-c7578200-c595-11e8-9302-735a66c0bfb2.png">

If we remove all mentions of `@yeild` and `@section` etc it works

**Comment by saleem-hadad** [comment]
Thank you @OwenMelbz for addressing this issue. I've one quick solution, you can use double @@ instead of one @. That will solve the issue 💃

**Comment by saleem-hadad** [comment]
I mean instead of @section => @@section
