### ISSUE TITLE
Nested Menu Alignment

### ISSUE THREAD

**Issue by aftabnaveed** [saleem-hadad/larecipe#47]
If you have more than one level of menu entries the layout for some reason does not look right. I am not sure if this is known or by design. Here is the code: 

```
- ## Catalog
    - [Structure](/docs/{{version}}/catalog/structure)
    - [Documents](/docs/{{version}}/catalog/documents)
        - [Product](/docs/{{version}}/catalog/documents/product)
        - [Category](/docs/{{version}}/catalog/documents/catrgory)
```
And the Screenshot:

![nested-menu](https://user-images.githubusercontent.com/58515/46379945-d2b8c380-c6e3-11e8-961b-5121c036a2aa.png)

**Comment by tankerkiller125** [comment]
I think this is by design, but I would like to see nested menus be supported, possibly has a hidden menu kind of option (think laravel docs)

**Comment by saleem-hadad** [comment]
Thank you @aftabnaveed for addressing this issue. Yes, that's correct the library support only one level of nested menu. However, you can add your custom CSS to support that as well or I'll add this request to the future development ( #6 ).
