### ISSUE TITLE
Subdomain configuration

### ISSUE THREAD

**Issue by kevindesousa** [saleem-hadad/larecipe#48]
Hello,

I think, it can be a good feature to set a custom subdomain instead a path on the principal domain.

We can have `docs.mydomain.tld` for example.

**Comment by phannaly** [comment]
@kevindesousa You can use subdomain but still have `docs` in URL. If you want to remove `docs` without touching code, you can reverse `domain.com/docs/` to `sub.domain.com` through `nginx`.

**Comment by saleem-hadad** [comment]
As @phannaly said you can configure that easily using nginx, or you can put your code on a sub-domain and then change the docs route to empty one to point to `docs.domain.com` instead of 'docs.domain.com/docs'. 
However, we'll consider this feature in the future development (#6). 
Thank you 👍

**Comment by kevindesousa** [comment]
Hello,
Thanks for the solution.
But I want to do this with nginx, but I don't know how.
```
    location / {
        index  index.php index.html index.htm;
        try_files $uri $uri/ /index.php$is_args$args;
    }
```
Can you help me please ?

**Comment by phannaly** [comment]
Hi @saleem-hadad Are you developing this PR? If not I think we should probably make a document about subdomain on our docs how to do this.

**Comment by awebartisan** [comment]
Hi, any leads on this issue?

**Comment by mowses** [comment]
> Hello,
> Thanks for the solution.
> But I want to do this with nginx, but I don't know how.
> 
> ```
>     location / {
>         index  index.php index.html index.htm;
>         try_files $uri $uri/ /index.php$is_args$args;
>     }
> ```
> 
> Can you help me please ?

I dont know how to do it too, anyone help?

**Comment by saleem-hadad** [comment]
This is an example of Nginx config you need
```
# listen to port 80 here
...

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name subdomain.example.com;
    root /root/to/your/public/folder/in/laravel;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    index index.html index.htm index.php;

    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
```
