### ISSUE TITLE
Documentation Sub-list don't render properly

### ISSUE THREAD

**Issue by tankerkiller125** [saleem-hadad/larecipe#54]
**Describe the bug**
If you create a sub-list in the documentation the markdown renderer will automatically assume that it is a list for the sidebar on the right. And there is no way to get it to render properly.

**To Reproduce**
1. Create a regular documentation file with a header and a right sidebar menu
2. Create a couple of regular paragraphs (Separate the list out)
3. Create a unordered list with a sub-list

**Expected behavior**
Sub-list should render as sublist

**Desktop (please complete the following information):**
 - OS: Elementary OS 0.4 (Ubuntu 16.04 based)
 - Browser: Firefox 63.0b11 64bit
 - Version: 1.2.5

Edit: After further review of the HTML the markdown renderer is rendering it properly, this is a CSS issue of some kind.

**Comment by tankerkiller125** [comment]
This issue was apparently fixed in a recent update and I failed to force update the assets.

**Comment by saleem-hadad** [comment]
Thank you @tankerkiller125 👍
