### ISSUE TITLE
Suggestion: Consider adding v-cloak until docs are loaded.

### ISSUE THREAD

**Issue by surgiie** [saleem-hadad/larecipe#55]
Hi,

This is a great package and im loving it so far. However im noticing when my page loads
some of the vue components have it's html loaded before vuejs compiles it. This causes a brief moment for html to render unstyled content. In my case its the navbar. It renders the logo and brand name html unstyled before vue turns it into the nice navbar. I recommend adding the v-cloak directive to the content wrapper so that the html content is hidden until it has loaded:

 
```
<div v-cloak>
    //
</div>

<style>
  [v-cloak] {
    display: none;
  }
</style>
```

**Comment by tnylea** [comment]
Agreed! v-cloak would prevent the flicker before the docs load 👍

**Comment by saleem-hadad** [comment]
Thank you @surgiie for your suggestion. Yeah, agreed. I'll add it to the future development #6

**Comment by saleem-hadad** [comment]
done 👍  attached to a new batch v1.3.2
