### ISSUE TITLE
More than one documentation?

### ISSUE THREAD

**Issue by techfervor** [saleem-hadad/larecipe#60]
I was just wondering, what if someone wants to write more than one documentation?

**Something like this screenshot:**
![new](https://user-images.githubusercontent.com/41358116/47578109-28d8f980-d966-11e8-9f96-02cd2f86ce83.png)

Can this be done?

**Comment by phannaly** [comment]
Why not make it as versions?

**Comment by techfervor** [comment]
A version is an upgraded documentation, right. But what I am stating is that suppose we have multiple software on our website, and every software needs to be documented. So how to write their own individual documentation using your package? 
I mean, it can be an awesome feature.

![newnew](https://user-images.githubusercontent.com/41358116/47598445-53a06d80-d9b9-11e8-9896-d9d608989dbd.png)

**Comment by saleem-hadad** [comment]
Thank you @techfervor for your suggestion, but the core of this package is meant to be used for one software documentation
