### ISSUE TITLE
Menu is covering the content on iPad.

### ISSUE THREAD

**Issue by jjcsinke** [saleem-hadad/larecipe#61]
The package looks interesting for a project I'm running. I opened the demo on my ipad (normal 2018, logical resolution 768x1024) and the menu is in front of the content in portrait mode. Easy fix in css but thought I should mention it anyway.

![94bcc102-5067-4a0d-81d9-66d2506239b9](https://user-images.githubusercontent.com/19775698/47592060-0cdb5500-d972-11e8-90db-b5acd1dc187e.png)

**Comment by saleem-hadad** [comment]
It's part of the package's design actually, you can override that if you want by providing your own CSS and js files, [see here](https://larecipe.binarytorch.com.my/docs/1.2/custom-css-and-js).
