### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by kamov** [saleem-hadad/larecipe#64]
I install package and run install command, then without any change in config I point browser to /docs but I get 403 Forbidden

I double check that auth middleware is disabled. Checking route:list command, I can see "docs" route.

**Comment by kamov** [comment]
Not sure where was the problem, maybe cache. All other pages worked fine, only /docs not worked.

It start work day after I checked..

Thanks

**Comment by AEK-BKF** [comment]
Same here !
@kamov did you find a solution for this please ?
