### ISSUE TITLE
Blank screen IE 11

### ISSUE THREAD

**Issue by jackleblack-kpt** [saleem-hadad/larecipe#66]
**Describe the bug**
Hit documentation url on IE 11, HTML is visible until VueJS load and give blank page.

**To Reproduce**
1. Run https://larecipe.binarytorch.com.my/docs/1.2/overview on IE 11.
2. Blank page

**Expected behavior**
View documentation.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser IE
 - Version 11

**Additional context**
IE11 doesn't support arrow function.
Maybe replace "mix.js" with "mix.babel" in file "webpack.mix" ?

**Comment by saleem-hadad** [comment]
is this error still exist?

**Comment by LarsN** [comment]
Yes, this is still an issue.

BR,
Lars

to 7. helmik. 2019 klo 14.50 Saleem Hadad (notifications@github.com)
kirjoitti:
