### ISSUE TITLE
btn-link on login page is missing custom css

### ISSUE THREAD

**Issue by jesperholstjh** [saleem-hadad/larecipe#68]
**Describe the bug**
The "forgot your password?" link on the login-page is not styled with custom colors.

**To Reproduce**
- Go to login page.
- See that the link is purple and does not honor the custom color you can set in the config.

Seems that the btn btn-link class is missing here: https://github.com/saleem-hadad/larecipe/blob/master/resources/views/partials/style.blade.php

**Comment by saleem-hadad** [comment]
Hi @jesperholstjh 
Actually, this package is meant to be without any pre-made auth pages, we left that for the developer to build his own UI
