### ISSUE TITLE
Does this package support multiple languages? (in development)

### ISSUE THREAD

**Issue by aFluxx** [saleem-hadad/larecipe#69]
**Is your feature request related to a problem? Please describe.**
It's more a question then a feature request, but I had to choose and I'm definitely not reporting a bug.

**Describe the solution you'd like**
I was wondering if it's possible to supply docs in multiple languages.

**Additional context**
I use this package for localization.
https://github.com/mcamara/laravel-localization
And this works with the following syntax 
`__('String to translate')`

But I'm not sure if this will work in the .md files.

**Comment by saleem-hadad** [comment]
Hi @aFluxx , thanks for your concern, actually, there is a plan for implementing this feature hopefully in the next major version next month 👍 
I'll leave this issue open.

**Comment by rayoplateado** [comment]
Hi! Any news on this?

**Comment by aFluxx** [comment]
@saleem-hadad looking forward to this update!

**Comment by saleem-hadad** [comment]
I'm currently working with my team on a private project, once I finish I'll come back developing this for sure hopefully within two weeks will be ready @aFluxx @rayoplateado

**Comment by saleem-hadad** [comment]
also, I'm working on two things for this package:
1. build-in search (almost done, need UI only)
2. convert to Tailwind CSS

**Comment by abhi-cognitivo** [comment]
Hi,

Since my documentation doesn't require versioning, I actually changed the version numbers to language.

Change 

-docs
-- en
--- index.md
--- overview.md
-- es
--- index.md
--- overview.md

And change the config file as follows:

```
    'versions'      => [
        'default'   => 'en',
        'published' => [
            'es',
            'en'
        ]
    ],

```

**Comment by abhi-cognitivo** [comment]
This isn't directly related to the question, but in case some one else wants to know:

I am developing a SAAS application and as such, version's aren't that important (since there is only one version of the app on the server). So I updated the configuration file to show language tags instead...

    'versions'      => [
        'default'   => 'en',
        'published' => [
            'es',
            'en'
        ]
    ], 

and on the folder structure did the same
- docs
-- en
--- index.md
--- overview.md
-- es
--- index.md
--- vista.md

It works out pretty great, plus you get the language key on the url, so you can direct users based on their preferences.

Hope this helps!

**Comment by saleem-hadad** [comment]
Hello everyone 
Now after I finished the internal search I'm planning to start working on this feature in parallel with RTL support. However, I have a concern about how do you suggest to implement it? 
I'm thinking that the relationship between a version and its languages is one to many.
Something like:
```php
'versions'       => [
    'default'    => '1.0',
    'published'  => [
        '1.0'    => [
            'en' => 'ltr',
            'ar' => 'rtl'
        ],
        '1.1'    => [
            'en' => 'ltr',
        ]
    ]
],
```

what do you think guys?

**Comment by abhi-cognitivo** [comment]
Suggestion:

If you are planning to introduce Language Support, there really is no
reason to specify RTL or not, since the languages that use RTL are standard
(mainly he [hebrew] and ar [arabic], more info here
<https://en.wikipedia.org/wiki/Right-to-left>)

So why not just create constant values and if the desired language hits ony
of those keys, automatically shift to RTL. This will avoid incorrect
configuration and will greatly simply your configuration structure to
include a basic array.

*Example*:

'versions'       => [    'default'    => '1.0',    'published'  => [
     '1.0'    => [ 'en', 'ar' ],        '1.1'    => [ 'en' ]    ]],

**Comment by saleem-hadad** [comment]
Sounds simple now :D thank you @abhi-cognitivo

**Comment by saleem-hadad** [comment]
Obviously implementing this feature will break a lot of existing usages (I mean it gonna be a major update) since the docs folder's structure will be changed.
However, do you prefer the path to be `/docs/1.1/en/page` or `/docs/en/1.1/page`?

**Comment by abhi-cognitivo** [comment]
@saleem-hadad , language should be before version, as people don't change languages but can and will change versions quite often.

But if you are going to do this, I would suggest applying both Version and Language as an optional feature, similar to what you do with Github Link or Search. Not every one will have multiple languages, and not every one will have multiple versions.

Currently I am using version as language and it works great: Here is a screenshot:

<img width="1440" alt="screen shot 2019-02-11 at 7 53 51 am" src="https://user-images.githubusercontent.com/12589654/52558978-c13ea100-2dd2-11e9-9c17-336a1243b14e.png">

**Comment by AMAFsoft** [comment]
Any news on this features??

**Comment by aFluxx** [comment]
Hello there,

I was going through my old tickets and I came across this one. Was wondering how far this is coming along. I'm writing a SaaS application and I'm nearing completion so I'm probably going to write some documentation for it.

If this feature is still in development phase I might use @abhi-cognitivo 's idea to use versioning for translations.

Thanks in advance for an update!

**Comment by saleem-hadad** [comment]
Hi, @aFluxx, I'm sorry for the late reply I was really busy the last two weeks.
I started working on this feature, hopefully, will be ready by 15/6/2019

**Comment by saleem-hadad** [comment]
will be added to the pro version as stated [here](https://github.com/saleem-hadad/larecipe/issues/6#issuecomment-568933034)

**Comment by hanifhefaz** [comment]
Hello @saleem-hadad 

Are there any updates of implementing right to left?

**Comment by saleem-hadad** [comment]
> Hello @saleem-hadad
> 
> Are there any updates of implementing right to left?

@hanifhefaz you can use this package for now
https://github.com/larecipe/rtl
