### ISSUE TITLE
Error during the installation with Composer under Laravel 5.7.1

### ISSUE THREAD

**Issue by cavo789** [saleem-hadad/larecipe#7]
**Describe the bug**
Error during the installation with Composer under Laravel 5.7.1.

The installation doesn't work but it's probably because I'm testing a lot of stuff on my "test" site.

**To Reproduce**
C:\Christophe\test>composer require binarytorch/larecipe
Using version ^1.0 for binarytorch/larecipe
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install binarytorch/larecipe v1.0.1
    - Conclusion: don't install binarytorch/larecipe v1.0.0
    - Conclusion: remove symfony/dom-crawler v3.4.15
    - Installation request for binarytorch/larecipe ^1.0 -> satisfiable by binarytorch/larecipe[1.0.x-dev, v1.0.0, v1.0.1].
    - Conclusion: don't install symfony/dom-crawler v3.4.15
    - binarytorch/larecipe 1.0.x-dev requires symfony/dom-crawler ^4.1 -> satisfiable by symfony/dom-crawler[4.1.x-dev, 4.2.x-dev, v4.1.0, v4.1.0-BETA1, v4.1.0-BETA2, v4.1.0-BETA3, v4.1.1, v4.1.2, v4.1.3, v4.1.4].
    - Can only install one of: symfony/dom-crawler[4.1.x-dev, v3.4.15].
    - Can only install one of: symfony/dom-crawler[4.2.x-dev, v3.4.15].
    - Can only install one of: symfony/dom-crawler[v4.1.0, v3.4.15].
    - Can only install one of: symfony/dom-crawler[v4.1.0-BETA1, v3.4.15].
    - Can only install one of: symfony/dom-crawler[v4.1.0-BETA2, v3.4.15].
    - Can only install one of: symfony/dom-crawler[v4.1.0-BETA3, v3.4.15].
    - Can only install one of: symfony/dom-crawler[v4.1.1, v3.4.15].
    - Can only install one of: symfony/dom-crawler[v4.1.2, v3.4.15].
    - Can only install one of: symfony/dom-crawler[v4.1.3, v3.4.15].
    - Can only install one of: symfony/dom-crawler[v4.1.4, v3.4.15].
    - Installation request for symfony/dom-crawler (locked at v3.4.15) -> satisfiable by symfony/dom-crawler[v3.4.15].

Installation failed, reverting ./composer.json to its original content.

**Expected behavior**

**Screenshots**

**Desktop:**
 - Windows 10 64bits

**Comment by cavo789** [comment]
More info: installation is OK on a new installation (`Laravel new larecipe`) but still not on my `test` site even after a `composer update` (and thus with Laravel 5.7.2)

**Comment by saleem-hadad** [comment]
Hi @cavo789 
Thank you for addressing the issue. However, I went through the installation process with one of my current projects which has more than 200 tests and it seems to work just fine.
Could you please share your project's dependencies here?

**Comment by cavo789** [comment]
Hi Saleem,

I've just tried again on Laravel 5.7.3 and it's OK (I've first make a composer update).

I was under 5.7.1; perhaps something wrong with that version of Laravel since 5.7.2 was there very fast and now 5..7.3.

This issue can, for me, be closed.

Thanks and have a nice day.

**Comment by saleem-hadad** [comment]
Happy to hear that 🤠 have a nice day to you too.
