### ISSUE TITLE
Gate returns error when using Laravel Bouncer

### ISSUE THREAD

**Issue by scottybo** [saleem-hadad/larecipe#75]
**Describe the bug**
We use [Laravel Bouncer](https://github.com/JosephSilber/bouncer) to manage permissions for our Laravel app. When attempting to add the LaRecipe gate to `/app/Providers/AuthServiceProvider.php` we get the following error:

```
Too few arguments to function BinaryTorch\LaRecipe\DocumentationRepository::__construct(), 0 passed in /var/www/html/holly-spark/vendor/silber/bouncer/src/CachedClipboard.php on line 170 and exactly 1 expected
```

**To Reproduce**
1. Install Laravel Bouncer
2. Install LaRecipe
3. Add a Gate

**Expected behavior**
An error shouldn't be thrown.

**Comment by saleem-hadad** [comment]
is this error still exist? @scottybo

**Comment by asivaneswaran** [comment]
I am this issue. Anyone can help me?
