### ISSUE TITLE
Button component link

### ISSUE THREAD

**Issue by crumb1e** [saleem-hadad/larecipe#79]
The docs don't explain how to give a `larecipe-button` component a link. I can see `handleClick()` on the actual vue component, but how can we set this?

**Comment by saleem-hadad** [comment]
Simple you can do this:

```
<larecipe-button @click="doWhatEverYouWantFunction">
    Example button
</larecipe-button>
```

**Comment by saleem-hadad** [comment]
or you can do this:

```js
<larecipe-button is="a" href="yourLink.com">
    Example button
</larecipe-button>
```

**Comment by stefaniacr** [comment]
Hi there! I-m new here, but I couldnt get any results by doing the proposed solution on the href. 
It doest take the button property if I add the href. Is there another workaround?

THanks much!!

**Comment by saleem-hadad** [comment]
can you please share your .md content?

**Comment by stefaniacr** [comment]
nvm ui was missing the tag in order to see it :
<larecipe-button tag="a" href="XXXXX">
                Button
            </larecipe-button>

**Comment by stefaniacr** [comment]
`<larecipe-button tag="a" href="..l"> Button</larecipe-button>`
