### ISSUE TITLE
embed the docs on frontend?

### ISSUE THREAD

**Issue by mpixelz** [saleem-hadad/larecipe#80]
**Is your feature request related to a problem? Please describe.**
im working on a saas application.. where we need to show documentation while they are using the application instead of them going to the separate page.. like a sidebar..

**Describe the solution you'd like**
option to embed the docs within a notification sidebar?
just like the default notification sidebar in laravel.. we have another sidebar which is triggered thru another button for support.. it loads up a notification sidebar but i dont know how i can embed larecipe package inside it.. so i can maintain one set of documentation while giving user to access it on all the pages.

any suggestions? 
p.s it would be something like `https://elev.io/` their support bubble.. where they have docs within the box.

**Comment by saleem-hadad** [comment]
Hi @mpixelz thanks for sharing this idea
I like the idea and this one of the upcoming features will be added to LaRecipe using built-in API that can be consumed to display the content from any client (Mobile, Front-End .. etc), see [here](https://github.com/saleem-hadad/larecipe/issues/6)

**Comment by mpixelz** [comment]
any news on this?
