### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by Ashu131** [saleem-hadad/larecipe#81]
**Your requirements could not be resolved to an installable set of packages.**
Problems:
  - Installation request for binarytorch/larecipe ^1.3 -> satisfiable by binarytorch/larecipe[v1.3.0].
  - binarytorch/larecipe v1.3.0 requires mockery/mockery ^1.2 -> satisfiable by mockery/mockery[1.2.0] but these conflict with your requirements or minimum-stability.

**To Reproduce**
Run
`composer require binarytorch/larecipe`

**Screenshots**
![larecipe installation error](https://user-images.githubusercontent.com/25302874/52408866-e04ee180-2af9-11e9-9967-fc026195dc63.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Mozilla Firefox
 - version: Latest

**Comment by saleem-hadad** [comment]
hmm, 🥺I've tried now to install it on a fresh Laravel project and it works.
can you paste your composer.json please?

**Comment by saleem-hadad** [comment]
anyway, I've removed mockery/mockery since we don't use it and I just released a new batch v1.3.1
try this one :) hopefully will work
