### ISSUE TITLE
js error when searching

### ISSUE THREAD

**Issue by jesperholstjh** [saleem-hadad/larecipe#82]
**Describe the bug**
When searching and entering specific characters, it throws an js error:
app.js:formatted:8280 TypeError: Cannot read property 'key' of undefined

It only happens to some characters, like "e", "o" i.e. Can't find a pattern though.
They have to be the start character, if writing them in a word like "header" it works fine.

Using version 1.3.0

**To Reproduce**
Start a search with above characters. 

**Desktop (please complete the following information):**
 - OS: Win10x64
 - Browser: Chrome
 - Version  71.0.3578.98

**Comment by saleem-hadad** [comment]
hmm that's interesting 🥺
I've tried to search with the letters you mention it works fine, I couldn't reproduce the error
However, could please clear your cache and try again?

**Comment by saleem-hadad** [comment]
<img width="775" alt="screenshot 2019-02-07 at 8 47 12 pm" src="https://user-images.githubusercontent.com/12780866/52412310-51ea5800-2b19-11e9-9e4f-025e371f02d8.png">

**Comment by jesperholstjh** [comment]
When searching for "headers" it works fine, as there is a result. 
But when searching for 'headerstest' it just displays a blank field, no errors. (See here: https://cdn3.imggmi.com/uploads/2019/2/8/7b33cba937c936a4bc8552fc41912165-full.png)

But when searching with 'e', 'o' etc it just throws the error:

TypeError: "e is undefined" - app.js:formatted:8242
    function Ve(e, t, n) {
      if (!W && !X || 'undefined' == typeof console) throw e;
      console.error(e)
    }

Cache is cleared. Both on server and browser.

**Comment by saleem-hadad** [comment]
:( unfortunately, I couldn't reproduce the same error. If you have a live version to check that would be awesome

**Comment by saleem-hadad** [comment]
Hi @jesperholstjh ,
is this bug still there?
