### ISSUE TITLE
Allow to Include files into a document

### ISSUE THREAD

**Issue by patriziotomato** [saleem-hadad/larecipe#84]
**Is your feature request related to a problem? Please describe.**
In our project there is a "general" documentation within a package. A concrete vendor needs to overwrite some of these files. If you can include files this would be easy to solve.

**Describe the solution you'd like**
Any syntax to include another file

**Describe alternatives you've considered**
Did not consider anything else so far

**Additional context**

**Comment by saleem-hadad** [comment]
Hmm, I'm really sorry but I couldn't understand the requested feature can you explain it more or provide images?

**Comment by patriziotomato** [comment]
Sorry, well, I just mean to include a second *.md file into another one. Like a usual `include()` method in php.

**Comment by saleem-hadad** [comment]
Cool
I'll add this feature to the upcoming development path :) see [here](https://github.com/saleem-hadad/larecipe/issues/6)

**Comment by patriziotomato** [comment]
nice. thank you!

**Comment by tarampampam** [comment]
This will be great feature!

**Comment by tarampampam** [comment]
Now I include files using next blade directive:

```php
namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register(): void
    {
        $this->app->afterResolving('blade.compiler', function (BladeCompiler $blade): void {
            $blade->directive('include_file', function (string $path): string {
                $path = base_path(\trim($path, '\'"\\/'));

                if (! \is_file($path)) {
                    throw new \InvalidArgumentException("File [$path] was not found");
                }

                return \file_get_contents($path);
            });
        });
    }
}
```

And then in any **markdown** file, for example:

```markdown
@include_file(some/file.txt)
```
