### ISSUE TITLE
Specify: Logout Path

### ISSUE THREAD

**Issue by StanBarrows** [saleem-hadad/larecipe#85]
Currently I'm using Laravel Nova for a project. With Nova my Default Logout Path is not "/logout". Because of this I'm running straight into a 404 Error after hitting the logout button. 

**Request:**
- [ ] Easy way to specify the logout path
- [ ] Possibility to enable or disable the Logout button

**Workaround**
As a dirty workaround, I disabled the logout component within the vendor folder.

```
       <larecipe-dropdown>
                <larecipe-button slot="title" type="secondary" class="dropdown-toggle btn-white ml-2">
                    {{ auth()->user()->name ?? 'Account' }}
                </larecipe-button>

                @if(config('larecipe.settings.auth_links') !== null)
                    @foreach(config('larecipe.settings.auth_links') as $link)
                        @if($link['url'] !== '')
                            <li>
                                <a href="{{ $link['url'] }}" class="dropdown-item">{{ $link['name'] }}</a>
                            </li>
                        @endif
                    @endforeach
                @endif

                <form action="/logout" method="POST">
                    {{ csrf_field() }}

                    <button class="dropdown-item" type="submit">Logout</button>
                </form>
            </larecipe-dropdown>

```
### Button inside the Dropdown
![image](https://user-images.githubusercontent.com/10268813/52519061-1608dd00-2c56-11e9-978b-f84a5e36fcf4.png)

### Logout Path
![image](https://user-images.githubusercontent.com/10268813/52519082-58cab500-2c56-11e9-9fb4-0c5f6abb8279.png)

### 404 Error
![image](https://user-images.githubusercontent.com/10268813/52519065-1d2feb00-2c56-11e9-987a-ae5625374663.png)

**Comment by saleem-hadad** [comment]
Hmm, got it. 
I have a quick solution for you. Copy this [file](https://github.com/saleem-hadad/larecipe/blob/master/resources/views/partials/nav.blade.php) and put it under: `resources/vendor/larecipe/partials/nav.blade.php` and then configure it as you like :)

**Comment by StanBarrows** [comment]
Cool! Thanks very much. 

Would you accept a PR to add this into the auth config?

**Comment by saleem-hadad** [comment]
Most welcome :D 
yeah sure 👍
