### ISSUE TITLE
Mobile Search

### ISSUE THREAD

**Issue by nam-co** [saleem-hadad/larecipe#86]
Hi, first of all  thanks for the great package
I notice in mobile there's a little error, search results appear behind, wouldn't be better to include the search field inside the sidebar? like in the sample image, I uploading also a image notes some things I notice in the mobile version, thanks for everything

<img width="436" alt="screen shot 2019-02-11 at 12 47 04 pm" src="https://user-images.githubusercontent.com/3951529/52582676-c06e3500-2dfb-11e9-8a19-03837af776ee.png">
<img width="436" alt="screen shot 2019-02-11 at 12 46 33 pm" src="https://user-images.githubusercontent.com/3951529/52582679-c3692580-2dfb-11e9-8710-461ce4f3c0b9.png">

**Comment by nam-co** [comment]
or maybe this is a better idea, and just include extra links and versions on the sidebar in the bottom, just an idea

<img width="436" alt="screen shot 2019-02-11 at 12 47 04 pm" src="https://user-images.githubusercontent.com/3951529/52583065-b6006b00-2dfc-11e9-8b61-63c6fc737074.png">

**Comment by saleem-hadad** [comment]
Thank you @nam-co for sharing the bug
Now solved by @Maen1 and attached to a new release v1.3.5 💃

**Comment by nam-co** [comment]
Thanks @Maen1 and @saleem-hadad
