### ISSUE TITLE
Copy to clipboard

### ISSUE THREAD

**Issue by alexgiuvara** [saleem-hadad/larecipe#87]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to carefully select the snippet of code then copy to clipboard

**Describe the solution you'd like**
A top-right "Copy to clipboard" button over each snippet

**Comment by saleem-hadad** [comment]
I like the idea :D 
I'll add it to the waiting list [here](https://github.com/saleem-hadad/larecipe/issues/6)
Thank you @alexgiuvara
