### ISSUE TITLE
issue on file /config/larecipe.php

### ISSUE THREAD

**Issue by kalislami** [saleem-hadad/larecipe#88]
Hi, I've installed the latest version of LaRecipe in Laravel version 5.4 that I upgraded to 5.5.
but when I try to edit the config/larecipe.php file like logo, route, etc.. still no change from the docs view.
I confused on this part, anybody help me?

**Comment by saleem-hadad** [comment]
have you tried to run:
```
composer dump-autoload
```

**Comment by kalislami** [comment]
thank you for the respons,
I have tried that command, but still no change when I edit larecipe.php file.

**Comment by kalislami** [comment]
ah it solved when I clear config cache, but when I edit again, need to clear config cache again.

**Comment by saleem-hadad** [comment]
awesome :D
