### ISSUE TITLE
I am getting app.js:1 ReferenceError: theme is not defined

### ISSUE THREAD

**Issue by CraftLogan** [saleem-hadad/larecipe#89]
Every time I go to the docs route I just get a white screen and an error in the chrome javascript console that says app.js:1 ReferenceError: theme is not defined. Any ideas?

**Comment by saleem-hadad** [comment]
can you provide more information about the version and if you have updated the version or installed a fresh one? 
If you updated the version just make sure you publish the new assets and clear the cache in your browser

**Comment by CraftLogan** [comment]
I am running v1.3 

Here is some screenshots of my composer.json and package.json

I installed larecipe on a clean installation of Laravel and it works but still can't get it to work in my current project it is probably a dependency in my package.json.

<img width="397" alt="screen shot 2019-02-13 at 7 22 39 pm" src="https://user-images.githubusercontent.com/10950466/52753624-69b45700-2fc5-11e9-94c5-f45cdea35e1b.png">
<img width="312" alt="screen shot 2019-02-13 at 7 23 46 pm" src="https://user-images.githubusercontent.com/10950466/52753625-69b45700-2fc5-11e9-8c71-17b550c8e16b.png">
<img width="1673" alt="screen shot 2019-02-13 at 7 24 29 pm" src="https://user-images.githubusercontent.com/10950466/52753626-69b45700-2fc5-11e9-9513-043b887dc503.png">

**Comment by CraftLogan** [comment]
I updated 1.3 and removed and reinstalled. I also cleared the cache of laravel and my browser but still is not working.

**Comment by CraftLogan** [comment]
I fixed it with
` php artisan vendor:publish --tag=larecipe_assets --force`

You were right just needed to update ui assets. Sorry for waisting your time. It was in the upgrade documentation! Right in front of my eyes. LOL

Thanks again and I love Larecipe.

**Comment by saleem-hadad** [comment]
haha no worries :D that's happened a lot with me as well
Glad you get benefit out of LaRecipe 😍
