### ISSUE TITLE
(info) Artisan output - bad icons

### ISSUE THREAD

**Issue by cavo789** [saleem-hadad/larecipe#9]
Here is the output of Artisan, on a Windows 10 64bits machine.

![2018-09-08_12h05_03](https://user-images.githubusercontent.com/355999/45252982-6b675800-b35f-11e8-893c-fecae50ec57e.png)

You're using the `ðŸ` characters in your `vendor\binarytorch\larecipe\src\Commands\InstallCommand.php` file and the rendering isn't correct on my machinge;

**Comment by saleem-hadad** [comment]
I think that related to the OS itself or the terminal that you're using cus I've tried it on mac os and Linux and the icons are showing normally. 🧐

**Comment by cavo789** [comment]
Yes, can be... I've only Windows here.

**Comment by saleem-hadad** [comment]
No problem, I'll leave this issue open maybe someone has experience with it can help 👻
