### ISSUE TITLE
Custom CSS/JS and cache busting

### ISSUE THREAD

**Issue by ijpatricio** [saleem-hadad/larecipe#91]
**Describe the bug**
If the links to the custom CSS/JS are kept after making some changes, the brower will not reload them, will use the cached version.

**To Reproduce**
1. Make some custom CSS/JS
2. Add them in larecipe's config
3. Visit a documentation page.
4. Make changes to the file made in (1.)
5. Visit page again
6. Realize that changes were not affected. (don't be with inspector open and "disable cache" enabled)

**Expected behavior**
This is expected, as it's an asset, and browser will cache it.
"Similar" to Laravel Mix, we could add a random string as query param.
This means that every request will bust the browser cache, but it's better than having viewers always viewing older versions.

This could be achieved by changing on the default.blade.php

I didn't change the core, i just published views to `resources/views/vendor/larecipe` so they would be load from there, and made the changes...

I will gladly do PR, just wanted to check in with you If you would like it or not?

```
<link rel="stylesheet" type="text/css" href="{{ asset($css) . '?id=' .\Illuminate\Support\Str::random(8) }}">

(...)

<script type="text/javascript" src="{{ asset($js) . '?id=' .\Illuminate\Support\Str::random(8) }}"></script>
```

**Screenshots**
N/A

**Desktop (please complete the following information):**
All

**Smartphone (please complete the following information):**
All

**Additional context**
N/A

**Comment by saleem-hadad** [comment]
Awesome catch 💯 but we might lose some cache benefit with adding this feature especially if the custom CSS/JS files are huge but TBH I don't think this is the majority since most of the time the custom files are just small modification or enhancement made to suit the need.
 
Just proceed with it 💃👏 
Thank you a lot @ijpatricio 😍

**Comment by ijpatricio** [comment]
Thanks for feedback! Yeah, there's a caveat in always putting a random string, but also believe that in 99.9% of use case, it's just fine... ;) 

No worries, love to contribute, such a great project ❤️❤️❤️

Will proceed to PR then!

**Comment by arxeiss** [comment]
What about using [`filemtime()`](http://us2.php.net/manual/en/function.filemtime.php) function to generate `?id`? I know this is not perfect, but probably better than random string?
