### ISSUE TITLE
Share same file in different versions

### ISSUE THREAD

**Issue by Kamicloud** [saleem-hadad/larecipe#94]
Sometimes we have same content in different versions, like ErrorCodes,  i18n and etc.
The folder is
```
v1
    - apis/
    - error-codes.md
    - index.md
v1_1
    - apis/
    - error-codes.md
    - index.md
```
If each error code related to an exception, we may throw exception in any version of API. So all error-codes.md is same.
If file can be referenced by index.md, and don't need to write multiple file, it will be awesome.
```
v1
    - apis/
    - &error-codes
    - index.md
v1_1
    - apis/
    - &error-codes
    - index.md
shared
    - error-codes.md
```

**Comment by Arcesilas** [comment]
Hi.

Is it not possible to use symlinks, or even hardlinks?

**Comment by Kamicloud** [comment]
> Hi.
> 
> Is it not possible to use symlinks, or even hardlinks?

Symlinks will work in web server, but may not work in vcs or windows.

**Comment by Arcesilas** [comment]
Symlinks do work with git (i've just tested and git does index regular files and symlinks).

On an NTFS filesystem with recent Windows version (I cannot try and am not 100% sure since I don't use Windows at all), you can use soft links, symbolik links and junctions: https://docs.microsoft.com/en-us/windows/desktop/fileio/hard-links-and-junctions

Have you tried any?

**Comment by Kamicloud** [comment]
> Symlinks do work with git (i've just tested and git does index regular files and symlinks).
> 
> On an NTFS filesystem with recent Windows version (I cannot try and am not 100% sure since I don't use Windows at all), you can use soft links, symbolik links and junctions: https://docs.microsoft.com/en-us/windows/desktop/fileio/hard-links-and-junctions
> 
> Have you tried any?

I found that if I can keep content in a file like this
```
XSym
0017
4161ba626eac37d56dea34e89102dabe
../error-codes.md
lots of blanks
```
It works as a symlink on linux. I can just fill the content or copy an existed symlink file on windows instead of using command ln -s on linux. 
It solved my problem(code on windows and start server on linux), and I'm sure it won't works on windows server.
Symlink works with git maybe the same reason (maybe linux storage symlink in content, not in meta data and not have an empty line at the end of file)
Thanks
