### ISSUE TITLE
Publish views for customization

### ISSUE THREAD

**Issue by kalynrobinson** [saleem-hadad/larecipe#97]
**Is your feature request related to a problem? Please describe.**
I want to customize my templates to add links to the navbar. I specifically want a link to each page's relevant Github file.

**Describe the solution you'd like**
Publish Larecipe's views so the user can customize them.

**Describe alternatives you've considered**
Provide a configurable "slot" to display additional data in the navbar.

**Comment by AMAFsoft** [comment]
Same here!
hope you add this feature soon!
i want to change some codes like :

```PHP
{{ auth()->user()->name ?? 'Account' }}
```
to 
```PHP
{{ auth()->user()->fullname ?? 'Account' }}
```
and some language support

Thank you for this Super helpful project!

**Comment by saleem-hadad** [comment]
you can actually override them as normal just put the files in the resources/views/vendor/larecipe accordingly.
for instance, let's say you want to override the navbar
just copy the file  [nav.blade.php](https://github.com/saleem-hadad/larecipe/blob/master/resources/views/partials/nav.blade.php) and paste it under resources/views/vendor/larecipe/partials/nav.blade.php
and so on
